/**
 * Enumération définissant les colonnes affichables pour le tableau des PEI
 */
enum COLUMN_PEI {
  NUMERO_COMPLET = "NUMERO_COMPLET",
  NUMERO_INTERNE = "NUMERO_INTERNE",
  TYPE_PEI = "TYPE_PEI",
  DISPONIBILITE_TERRESTRE = "DISPONIBILITE_TERRESTRE",
  DISPONIBILITE_HBE = "DISPONIBILITE_HBE",
  NATURE = "NATURE",
  COMMUNE = "COMMUNE",
  NATURE_DECI = "NATURE_DECI",
  AUTORITE_DECI = "AUTORITE_DECI",
  SERVICE_PUBLIC_DECI = "SERVICE_PUBLIC_DECI",
  ANOMALIES = "ANOMALIES",
  PEI_NEXT_RECOP = "PEI_NEXT_RECOP",
  PEI_NEXT_CTP = "PEI_NEXT_CTP",
  TOURNEE_LIBELLE = "TOURNEE_LIBELLE",
  PEI_ADRESSE = "ADRESSE",
}
export default COLUMN_PEI;
