enum TYPE_RESUME_ELEMENT {
  TOURNEE = "TOURNEE",
  DISPONIBILITE = "DISPONIBILITE",
  ANOMALIES = "ANOMALIES",
  LOCALISATION = "LOCALISATION",
  CARACTERISTIQUES = "CARACTERISTIQUES",
  CIS = "CIS",
  CASERNE = "CASERNE",
  OBSERVATION = "OBSERVATION",
}
export default TYPE_RESUME_ELEMENT;
