/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.couverturehydraulique.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.locationtech.jts.geom.Geometry
import remocra.db.jooq.bindings.GeometryBinding
import remocra.db.jooq.couverturehydraulique.Couverturehydraulique
import remocra.db.jooq.couverturehydraulique.indexes.COUVERTURE_TRACEE_PEI_GEOMETRIE_IDX
import remocra.db.jooq.couverturehydraulique.keys.COUVERTURE_TRACEE_PEI_PKEY
import remocra.db.jooq.couverturehydraulique.keys.COUVERTURE_TRACEE_PEI__COUVERTURE_TRACEE_PEI_COUVERTURE_TRACEE_PEI_ETUDE_ID_FKEY
import remocra.db.jooq.couverturehydraulique.tables.Etude.EtudePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class CouvertureTraceePei(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Couverturehydraulique.COUVERTUREHYDRAULIQUE,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>couverturehydraulique.couverture_tracee_pei</code>
         */
        val COUVERTURE_TRACEE_PEI: CouvertureTraceePei = CouvertureTraceePei()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column
     * <code>couverturehydraulique.couverture_tracee_pei.couverture_tracee_pei_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("couverture_tracee_pei_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>couverturehydraulique.couverture_tracee_pei.couverture_tracee_pei_etude_id</code>.
     */
    val ETUDE_ID: TableField<Record, UUID?> = createField(DSL.name("couverture_tracee_pei_etude_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>couverturehydraulique.couverture_tracee_pei.couverture_tracee_pei_distance</code>.
     */
    val DISTANCE: TableField<Record, Int?> = createField(DSL.name("couverture_tracee_pei_distance"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column
     * <code>couverturehydraulique.couverture_tracee_pei.couverture_tracee_pei_geometrie</code>.
     */
    val GEOMETRIE: TableField<Record, Geometry?> = createField(DSL.name("couverture_tracee_pei_geometrie"), SQLDataType.GEOMETRY, this, "", GeometryBinding())

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased
     * <code>couverturehydraulique.couverture_tracee_pei</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased
     * <code>couverturehydraulique.couverture_tracee_pei</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>couverturehydraulique.couverture_tracee_pei</code> table
     * reference
     */
    constructor() : this(DSL.name("couverture_tracee_pei"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, COUVERTURE_TRACEE_PEI, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = [
            "https://www.jooq.org",
            "jOOQ version:3.20.10",
        ],
        comments = "This class is generated by jOOQ",
    )
    open class CouvertureTraceePeiPath : CouvertureTraceePei, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): CouvertureTraceePeiPath = CouvertureTraceePeiPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CouvertureTraceePeiPath = CouvertureTraceePeiPath(alias, this)
        override fun `as`(alias: Table<*>): CouvertureTraceePeiPath = CouvertureTraceePeiPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Couverturehydraulique.COUVERTUREHYDRAULIQUE
    override fun getIndexes(): List<Index> = listOf(COUVERTURE_TRACEE_PEI_GEOMETRIE_IDX)
    override fun getPrimaryKey(): UniqueKey<Record> = COUVERTURE_TRACEE_PEI_PKEY
    override fun getReferences(): List<ForeignKey<Record, *>> = listOf(COUVERTURE_TRACEE_PEI__COUVERTURE_TRACEE_PEI_COUVERTURE_TRACEE_PEI_ETUDE_ID_FKEY)

    /**
     * Get the implicit join path to the
     * <code>couverturehydraulique.etude</code> table.
     */
    fun etude(): EtudePath = etude
    val etude: EtudePath by lazy { EtudePath(this, COUVERTURE_TRACEE_PEI__COUVERTURE_TRACEE_PEI_COUVERTURE_TRACEE_PEI_ETUDE_ID_FKEY, null) }
    override fun `as`(alias: String): CouvertureTraceePei = CouvertureTraceePei(DSL.name(alias), this)
    override fun `as`(alias: Name): CouvertureTraceePei = CouvertureTraceePei(alias, this)
    override fun `as`(alias: Table<*>): CouvertureTraceePei = CouvertureTraceePei(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CouvertureTraceePei = CouvertureTraceePei(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CouvertureTraceePei = CouvertureTraceePei(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CouvertureTraceePei = CouvertureTraceePei(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CouvertureTraceePei = CouvertureTraceePei(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CouvertureTraceePei = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CouvertureTraceePei = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CouvertureTraceePei = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CouvertureTraceePei = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CouvertureTraceePei = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CouvertureTraceePei = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CouvertureTraceePei = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CouvertureTraceePei = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CouvertureTraceePei = where(DSL.notExists(select))
}
