/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.couverturehydraulique.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.couverturehydraulique.Couverturehydraulique
import remocra.db.jooq.couverturehydraulique.keys.ETUDE__ETUDE_ETUDE_TYPE_ETUDE_ID_FKEY
import remocra.db.jooq.couverturehydraulique.keys.TYPE_ETUDE_PKEY
import remocra.db.jooq.couverturehydraulique.keys.TYPE_ETUDE_TYPE_ETUDE_CODE_KEY
import remocra.db.jooq.couverturehydraulique.tables.Etude.EtudePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.3",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class TypeEtude(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Couverturehydraulique.COUVERTUREHYDRAULIQUE,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>couverturehydraulique.type_etude</code>
         */
        val TYPE_ETUDE: TypeEtude = TypeEtude()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>couverturehydraulique.type_etude.type_etude_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("type_etude_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>couverturehydraulique.type_etude.type_etude_actif</code>.
     */
    val ACTIF: TableField<Record, Boolean?> = createField(DSL.name("type_etude_actif"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>couverturehydraulique.type_etude.type_etude_code</code>.
     */
    val CODE: TableField<Record, String?> = createField(DSL.name("type_etude_code"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>couverturehydraulique.type_etude.type_etude_libelle</code>.
     */
    val LIBELLE: TableField<Record, String?> = createField(DSL.name("type_etude_libelle"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>couverturehydraulique.type_etude</code> table
     * reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>couverturehydraulique.type_etude</code> table
     * reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>couverturehydraulique.type_etude</code> table reference
     */
    constructor() : this(DSL.name("type_etude"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TYPE_ETUDE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TypeEtudePath : TypeEtude, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): TypeEtudePath = TypeEtudePath(DSL.name(alias), this)
        override fun `as`(alias: Name): TypeEtudePath = TypeEtudePath(alias, this)
        override fun `as`(alias: Table<*>): TypeEtudePath = TypeEtudePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Couverturehydraulique.COUVERTUREHYDRAULIQUE
    override fun getPrimaryKey(): UniqueKey<Record> = TYPE_ETUDE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(TYPE_ETUDE_TYPE_ETUDE_CODE_KEY)

    private lateinit var _etude: EtudePath

    /**
     * Get the implicit to-many join path to the
     * <code>couverturehydraulique.etude</code> table
     */
    fun etude(): EtudePath {
        if (!this::_etude.isInitialized) {
            _etude = EtudePath(this, null, ETUDE__ETUDE_ETUDE_TYPE_ETUDE_ID_FKEY.inverseKey)
        }

        return _etude
    }

    val etude: EtudePath
        get(): EtudePath = etude()
    override fun `as`(alias: String): TypeEtude = TypeEtude(DSL.name(alias), this)
    override fun `as`(alias: Name): TypeEtude = TypeEtude(alias, this)
    override fun `as`(alias: Table<*>): TypeEtude = TypeEtude(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TypeEtude = TypeEtude(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TypeEtude = TypeEtude(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TypeEtude = TypeEtude(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TypeEtude = TypeEtude(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TypeEtude = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TypeEtude = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TypeEtude = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TypeEtude = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TypeEtude = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TypeEtude = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TypeEtude = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TypeEtude = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TypeEtude = where(DSL.notExists(select))
}
