services:
  db:
    image: postgis/postgis:16-3.4
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USERNAME:-remocra}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD:-remocra}
      - POSTGRES_DB=remocra
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${DOSSIER_BDD:-./.docker/postgresql_data}:/var/lib/postgresql/data

  keycloak:
    image: docker-registry.priv.atolcd.com/keycloak/base:26
    user: "${UID:-1000}:${GID:-1000}"
    command: [ "start-dev" ]
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME=kcadmin
      - KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD=kcadmin
    volumes:
      - ./keycloak/src/theme:/opt/keycloak/themes/remocra:ro
      - ./.data/images/ressources:/opt/keycloak/themes/remocra/login/resources/img:ro
      - ./.docker/keycloak:/opt/keycloak/data

  keycloak-config:
    image: docker-registry.priv.atolcd.com/keycloak/base:26
    command: [ "keycloak-config-cli" ]
    environment:
      # configuration de keycloak-config-cli (https://gerrit.priv.atolcd.com/plugins/gitiles/atolcd/docker#keycloak_base)
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_USER=kcadmin
      - KEYCLOAK_PASSWORD=kcadmin
      - IMPORT_FILES_LOCATIONS=/config/prod/*.json,/config/dev/*.json
      # configuration du realm "remocra"
      - CLIENT_SECRET=remocra
      - REMOCRA_URL=http://localhost:8881
    volumes:
      - ./keycloak/src/conf:/config:ro

  geoserver:
    build:
      context: geoserver
      target: dev
      pull: true
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 8090:8080
    volumes:
      - ./.docker/geoserver:/var/opt/geoserver
      - ./.data/images/symbologie:/var/opt/geoserver/workspaces/remocra/styles/symbologie:ro

  geoserver-config:
    build:
      context: geoserver
      target: dev
      pull: true
    command: [ "load-data" ]
    environment:
      - GEOSERVER_URL=http://geoserver:8080/geoserver
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=geoserver
      - POSTGIS_HOSTNAME=db
      - POSTGIS_USER=remocra
      - POSTGIS_PASSWORD=remocra
    volumes:
      - ./geoserver/load-data.sh:/usr/local/bin/load-geoserver-data.sh:ro
      - ./geoserver/data:/data:ro

  maildev:
    image: maildev/maildev:latest
    ports:
      - "1025:1025"
      - "1080:1080"
