/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.CONTACT__CONTACT_CONTACT_FONCTION_FKEY
import remocra.db.jooq.remocra.keys.FONCTION_CONTACT_FONCTION_CONTACT_CODE_KEY
import remocra.db.jooq.remocra.keys.FONCTION_CONTACT_PKEY
import remocra.db.jooq.remocra.tables.Contact.ContactPath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class FonctionContact(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.fonction_contact</code>
         */
        val FONCTION_CONTACT: FonctionContact = FonctionContact()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.fonction_contact.fonction_contact_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("fonction_contact_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>remocra.fonction_contact.fonction_contact_actif</code>.
     */
    val ACTIF: TableField<Record, Boolean?> = createField(DSL.name("fonction_contact_actif"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.fonction_contact.fonction_contact_protected</code>.
     */
    val PROTECTED: TableField<Record, Boolean?> = createField(DSL.name("fonction_contact_protected"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>remocra.fonction_contact.fonction_contact_code</code>.
     */
    val CODE: TableField<Record, String?> = createField(DSL.name("fonction_contact_code"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.fonction_contact.fonction_contact_libelle</code>.
     */
    val LIBELLE: TableField<Record, String?> = createField(DSL.name("fonction_contact_libelle"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.fonction_contact</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.fonction_contact</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.fonction_contact</code> table reference
     */
    constructor() : this(DSL.name("fonction_contact"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, FONCTION_CONTACT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class FonctionContactPath : FonctionContact, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): FonctionContactPath = FonctionContactPath(DSL.name(alias), this)
        override fun `as`(alias: Name): FonctionContactPath = FonctionContactPath(alias, this)
        override fun `as`(alias: Table<*>): FonctionContactPath = FonctionContactPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = FONCTION_CONTACT_PKEY
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(FONCTION_CONTACT_FONCTION_CONTACT_CODE_KEY)

    private lateinit var _contact: ContactPath

    /**
     * Get the implicit to-many join path to the <code>remocra.contact</code>
     * table
     */
    fun contact(): ContactPath {
        if (!this::_contact.isInitialized) {
            _contact = ContactPath(this, null, CONTACT__CONTACT_CONTACT_FONCTION_FKEY.inverseKey)
        }

        return _contact
    }

    val contact: ContactPath
        get(): ContactPath = contact()
    override fun `as`(alias: String): FonctionContact = FonctionContact(DSL.name(alias), this)
    override fun `as`(alias: Name): FonctionContact = FonctionContact(alias, this)
    override fun `as`(alias: Table<*>): FonctionContact = FonctionContact(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): FonctionContact = FonctionContact(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FonctionContact = FonctionContact(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FonctionContact = FonctionContact(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): FonctionContact = FonctionContact(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): FonctionContact = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): FonctionContact = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): FonctionContact = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): FonctionContact = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): FonctionContact = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): FonctionContact = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): FonctionContact = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): FonctionContact = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): FonctionContact = where(DSL.notExists(select))
}
