/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE_PKEY
import remocra.db.jooq.remocra.keys.L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE__L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE_ELEMENT_ID_FKEY
import remocra.db.jooq.remocra.keys.L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE__L_ADRESSE_ELEMENT_ADRESSE_TYPE_AN_ADRESSE_TYPE_ANOMALIE_ID_FKEY
import remocra.db.jooq.remocra.tables.AdresseElement.AdresseElementPath
import remocra.db.jooq.remocra.tables.AdresseTypeAnomalie.AdresseTypeAnomaliePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class LAdresseElementAdresseTypeAnomalie(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>remocra.l_adresse_element_adresse_type_anomalie</code>
         */
        val L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE: LAdresseElementAdresseTypeAnomalie = LAdresseElementAdresseTypeAnomalie()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column
     * <code>remocra.l_adresse_element_adresse_type_anomalie.adresse_type_anomalie_id</code>.
     */
    val ADRESSE_TYPE_ANOMALIE_ID: TableField<Record, UUID?> = createField(DSL.name("adresse_type_anomalie_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.l_adresse_element_adresse_type_anomalie.element_id</code>.
     */
    val ELEMENT_ID: TableField<Record, UUID?> = createField(DSL.name("element_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased
     * <code>remocra.l_adresse_element_adresse_type_anomalie</code> table
     * reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased
     * <code>remocra.l_adresse_element_adresse_type_anomalie</code> table
     * reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.l_adresse_element_adresse_type_anomalie</code>
     * table reference
     */
    constructor() : this(DSL.name("l_adresse_element_adresse_type_anomalie"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class LAdresseElementAdresseTypeAnomaliePath : LAdresseElementAdresseTypeAnomalie, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): LAdresseElementAdresseTypeAnomaliePath = LAdresseElementAdresseTypeAnomaliePath(DSL.name(alias), this)
        override fun `as`(alias: Name): LAdresseElementAdresseTypeAnomaliePath = LAdresseElementAdresseTypeAnomaliePath(alias, this)
        override fun `as`(alias: Table<*>): LAdresseElementAdresseTypeAnomaliePath = LAdresseElementAdresseTypeAnomaliePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE_PKEY
    override fun getReferences(): List<ForeignKey<Record, *>> = listOf(L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE__L_ADRESSE_ELEMENT_ADRESSE_TYPE_AN_ADRESSE_TYPE_ANOMALIE_ID_FKEY, L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE__L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE_ELEMENT_ID_FKEY)

    private lateinit var _adresseTypeAnomalie: AdresseTypeAnomaliePath

    /**
     * Get the implicit join path to the
     * <code>remocra.adresse_type_anomalie</code> table.
     */
    fun adresseTypeAnomalie(): AdresseTypeAnomaliePath {
        if (!this::_adresseTypeAnomalie.isInitialized) {
            _adresseTypeAnomalie = AdresseTypeAnomaliePath(this, L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE__L_ADRESSE_ELEMENT_ADRESSE_TYPE_AN_ADRESSE_TYPE_ANOMALIE_ID_FKEY, null)
        }

        return _adresseTypeAnomalie
    }

    val adresseTypeAnomalie: AdresseTypeAnomaliePath
        get(): AdresseTypeAnomaliePath = adresseTypeAnomalie()

    private lateinit var _adresseElement: AdresseElementPath

    /**
     * Get the implicit join path to the <code>remocra.adresse_element</code>
     * table.
     */
    fun adresseElement(): AdresseElementPath {
        if (!this::_adresseElement.isInitialized) {
            _adresseElement = AdresseElementPath(this, L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE__L_ADRESSE_ELEMENT_ADRESSE_TYPE_ANOMALIE_ELEMENT_ID_FKEY, null)
        }

        return _adresseElement
    }

    val adresseElement: AdresseElementPath
        get(): AdresseElementPath = adresseElement()
    override fun `as`(alias: String): LAdresseElementAdresseTypeAnomalie = LAdresseElementAdresseTypeAnomalie(DSL.name(alias), this)
    override fun `as`(alias: Name): LAdresseElementAdresseTypeAnomalie = LAdresseElementAdresseTypeAnomalie(alias, this)
    override fun `as`(alias: Table<*>): LAdresseElementAdresseTypeAnomalie = LAdresseElementAdresseTypeAnomalie(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LAdresseElementAdresseTypeAnomalie = LAdresseElementAdresseTypeAnomalie(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LAdresseElementAdresseTypeAnomalie = LAdresseElementAdresseTypeAnomalie(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LAdresseElementAdresseTypeAnomalie = LAdresseElementAdresseTypeAnomalie(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LAdresseElementAdresseTypeAnomalie = LAdresseElementAdresseTypeAnomalie(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LAdresseElementAdresseTypeAnomalie = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LAdresseElementAdresseTypeAnomalie = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LAdresseElementAdresseTypeAnomalie = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LAdresseElementAdresseTypeAnomalie = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LAdresseElementAdresseTypeAnomalie = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LAdresseElementAdresseTypeAnomalie = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LAdresseElementAdresseTypeAnomalie = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LAdresseElementAdresseTypeAnomalie = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LAdresseElementAdresseTypeAnomalie = where(DSL.notExists(select))
}
