/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.L_CONTACT_ROLE_PKEY
import remocra.db.jooq.remocra.keys.L_CONTACT_ROLE__L_CONTACT_ROLE_CONTACT_ID_FKEY
import remocra.db.jooq.remocra.keys.L_CONTACT_ROLE__L_CONTACT_ROLE_ROLE_ID_FKEY
import remocra.db.jooq.remocra.tables.Contact.ContactPath
import remocra.db.jooq.remocra.tables.RoleContact.RoleContactPath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.9",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class LContactRole(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.l_contact_role</code>
         */
        val L_CONTACT_ROLE: LContactRole = LContactRole()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.l_contact_role.contact_id</code>.
     */
    val CONTACT_ID: TableField<Record, UUID?> = createField(DSL.name("contact_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>remocra.l_contact_role.role_id</code>.
     */
    val ROLE_ID: TableField<Record, UUID?> = createField(DSL.name("role_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.l_contact_role</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.l_contact_role</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.l_contact_role</code> table reference
     */
    constructor() : this(DSL.name("l_contact_role"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, L_CONTACT_ROLE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = [
            "https://www.jooq.org",
            "jOOQ version:3.20.9",
        ],
        comments = "This class is generated by jOOQ",
    )
    open class LContactRolePath : LContactRole, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): LContactRolePath = LContactRolePath(DSL.name(alias), this)
        override fun `as`(alias: Name): LContactRolePath = LContactRolePath(alias, this)
        override fun `as`(alias: Table<*>): LContactRolePath = LContactRolePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = L_CONTACT_ROLE_PKEY
    override fun getReferences(): List<ForeignKey<Record, *>> = listOf(L_CONTACT_ROLE__L_CONTACT_ROLE_CONTACT_ID_FKEY, L_CONTACT_ROLE__L_CONTACT_ROLE_ROLE_ID_FKEY)

    /**
     * Get the implicit join path to the <code>remocra.contact</code> table.
     */
    fun contact(): ContactPath = contact
    val contact: ContactPath by lazy { ContactPath(this, L_CONTACT_ROLE__L_CONTACT_ROLE_CONTACT_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>remocra.role_contact</code>
     * table.
     */
    fun roleContact(): RoleContactPath = roleContact
    val roleContact: RoleContactPath by lazy { RoleContactPath(this, L_CONTACT_ROLE__L_CONTACT_ROLE_ROLE_ID_FKEY, null) }
    override fun `as`(alias: String): LContactRole = LContactRole(DSL.name(alias), this)
    override fun `as`(alias: Name): LContactRole = LContactRole(alias, this)
    override fun `as`(alias: Table<*>): LContactRole = LContactRole(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LContactRole = LContactRole(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LContactRole = LContactRole(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LContactRole = LContactRole(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LContactRole = LContactRole(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LContactRole = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LContactRole = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LContactRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LContactRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LContactRole = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LContactRole = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LContactRole = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LContactRole = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LContactRole = where(DSL.notExists(select))
}
