/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.enums.TypeModule
import remocra.db.jooq.remocra.keys.L_COUCHE_MODULE_PKEY
import remocra.db.jooq.remocra.keys.L_COUCHE_MODULE__L_COUCHE_MODULE_COUCHE_ID_FKEY
import remocra.db.jooq.remocra.tables.Couche.CouchePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class LCoucheModule(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.l_couche_module</code>
         */
        val L_COUCHE_MODULE: LCoucheModule = LCoucheModule()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.l_couche_module.couche_id</code>.
     */
    val COUCHE_ID: TableField<Record, UUID?> = createField(DSL.name("couche_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>remocra.l_couche_module.module_type</code>.
     */
    val MODULE_TYPE: TableField<Record, TypeModule?> = createField(DSL.name("module_type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(TypeModule::class.java), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.l_couche_module</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.l_couche_module</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.l_couche_module</code> table reference
     */
    constructor() : this(DSL.name("l_couche_module"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, L_COUCHE_MODULE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = [
            "https://www.jooq.org",
            "jOOQ version:3.20.10",
        ],
        comments = "This class is generated by jOOQ",
    )
    open class LCoucheModulePath : LCoucheModule, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): LCoucheModulePath = LCoucheModulePath(DSL.name(alias), this)
        override fun `as`(alias: Name): LCoucheModulePath = LCoucheModulePath(alias, this)
        override fun `as`(alias: Table<*>): LCoucheModulePath = LCoucheModulePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = L_COUCHE_MODULE_PKEY
    override fun getReferences(): List<ForeignKey<Record, *>> = listOf(L_COUCHE_MODULE__L_COUCHE_MODULE_COUCHE_ID_FKEY)

    /**
     * Get the implicit join path to the <code>remocra.couche</code> table.
     */
    fun couche(): CouchePath = couche
    val couche: CouchePath by lazy { CouchePath(this, L_COUCHE_MODULE__L_COUCHE_MODULE_COUCHE_ID_FKEY, null) }
    override fun `as`(alias: String): LCoucheModule = LCoucheModule(DSL.name(alias), this)
    override fun `as`(alias: Name): LCoucheModule = LCoucheModule(alias, this)
    override fun `as`(alias: Table<*>): LCoucheModule = LCoucheModule(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LCoucheModule = LCoucheModule(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LCoucheModule = LCoucheModule(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LCoucheModule = LCoucheModule(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LCoucheModule = LCoucheModule(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LCoucheModule = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LCoucheModule = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LCoucheModule = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LCoucheModule = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LCoucheModule = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LCoucheModule = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LCoucheModule = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LCoucheModule = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LCoucheModule = where(DSL.notExists(select))
}
