/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.L_DASHBOARD_PROFIL_PROFIL_UTILISATEUR_ID_KEY
import remocra.db.jooq.remocra.keys.L_DASHBOARD_PROFIL__L_DASHBOARD_PROFIL_DASHBOARD_ID_FKEY
import remocra.db.jooq.remocra.keys.L_DASHBOARD_PROFIL__L_DASHBOARD_PROFIL_PROFIL_UTILISATEUR_ID_FKEY
import remocra.db.jooq.remocra.tables.Dashboard.DashboardPath
import remocra.db.jooq.remocra.tables.ProfilUtilisateur.ProfilUtilisateurPath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class LDashboardProfil(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.l_dashboard_profil</code>
         */
        val L_DASHBOARD_PROFIL: LDashboardProfil = LDashboardProfil()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.l_dashboard_profil.profil_utilisateur_id</code>.
     */
    val PROFIL_UTILISATEUR_ID: TableField<Record, UUID?> = createField(DSL.name("profil_utilisateur_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>remocra.l_dashboard_profil.dashboard_id</code>.
     */
    val DASHBOARD_ID: TableField<Record, UUID?> = createField(DSL.name("dashboard_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.l_dashboard_profil</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.l_dashboard_profil</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.l_dashboard_profil</code> table reference
     */
    constructor() : this(DSL.name("l_dashboard_profil"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, L_DASHBOARD_PROFIL, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class LDashboardProfilPath : LDashboardProfil, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): LDashboardProfilPath = LDashboardProfilPath(DSL.name(alias), this)
        override fun `as`(alias: Name): LDashboardProfilPath = LDashboardProfilPath(alias, this)
        override fun `as`(alias: Table<*>): LDashboardProfilPath = LDashboardProfilPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(L_DASHBOARD_PROFIL_PROFIL_UTILISATEUR_ID_KEY)
    override fun getReferences(): List<ForeignKey<Record, *>> = listOf(L_DASHBOARD_PROFIL__L_DASHBOARD_PROFIL_DASHBOARD_ID_FKEY, L_DASHBOARD_PROFIL__L_DASHBOARD_PROFIL_PROFIL_UTILISATEUR_ID_FKEY)

    private lateinit var _dashboard: DashboardPath

    /**
     * Get the implicit join path to the <code>remocra.dashboard</code> table.
     */
    fun dashboard(): DashboardPath {
        if (!this::_dashboard.isInitialized) {
            _dashboard = DashboardPath(this, L_DASHBOARD_PROFIL__L_DASHBOARD_PROFIL_DASHBOARD_ID_FKEY, null)
        }

        return _dashboard
    }

    val dashboard: DashboardPath
        get(): DashboardPath = dashboard()

    private lateinit var _profilUtilisateur: ProfilUtilisateurPath

    /**
     * Get the implicit join path to the <code>remocra.profil_utilisateur</code>
     * table.
     */
    fun profilUtilisateur(): ProfilUtilisateurPath {
        if (!this::_profilUtilisateur.isInitialized) {
            _profilUtilisateur = ProfilUtilisateurPath(this, L_DASHBOARD_PROFIL__L_DASHBOARD_PROFIL_PROFIL_UTILISATEUR_ID_FKEY, null)
        }

        return _profilUtilisateur
    }

    val profilUtilisateur: ProfilUtilisateurPath
        get(): ProfilUtilisateurPath = profilUtilisateur()
    override fun `as`(alias: String): LDashboardProfil = LDashboardProfil(DSL.name(alias), this)
    override fun `as`(alias: Name): LDashboardProfil = LDashboardProfil(alias, this)
    override fun `as`(alias: Table<*>): LDashboardProfil = LDashboardProfil(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LDashboardProfil = LDashboardProfil(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LDashboardProfil = LDashboardProfil(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LDashboardProfil = LDashboardProfil(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LDashboardProfil = LDashboardProfil(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LDashboardProfil = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LDashboardProfil = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LDashboardProfil = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LDashboardProfil = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LDashboardProfil = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LDashboardProfil = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LDashboardProfil = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LDashboardProfil = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LDashboardProfil = where(DSL.notExists(select))
}
