/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.enums.TypePei
import remocra.db.jooq.remocra.keys.L_DIAMETRE_NATURE__L_DIAMETRE_NATURE_NATURE_ID_FKEY
import remocra.db.jooq.remocra.keys.NATURE_NATURE_CODE_KEY
import remocra.db.jooq.remocra.keys.NATURE_PKEY
import remocra.db.jooq.remocra.keys.PEI__PEI_PEI_NATURE_ID_FKEY
import remocra.db.jooq.remocra.keys.POIDS_ANOMALIE__POIDS_ANOMALIE_POIDS_ANOMALIE_NATURE_ID_FKEY
import remocra.db.jooq.remocra.tables.Anomalie.AnomaliePath
import remocra.db.jooq.remocra.tables.Diametre.DiametrePath
import remocra.db.jooq.remocra.tables.LDiametreNature.LDiametreNaturePath
import remocra.db.jooq.remocra.tables.Pei.PeiPath
import remocra.db.jooq.remocra.tables.PoidsAnomalie.PoidsAnomaliePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.3",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class Nature(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.nature</code>
         */
        val NATURE: Nature = Nature()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.nature.nature_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("nature_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>remocra.nature.nature_actif</code>.
     */
    val ACTIF: TableField<Record, Boolean?> = createField(DSL.name("nature_actif"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>remocra.nature.nature_code</code>.
     */
    val CODE: TableField<Record, String?> = createField(DSL.name("nature_code"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>remocra.nature.nature_libelle</code>.
     */
    val LIBELLE: TableField<Record, String?> = createField(DSL.name("nature_libelle"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>remocra.nature.nature_type_pei</code>.
     */
    val TYPE_PEI: TableField<Record, TypePei?> = createField(DSL.name("nature_type_pei"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(TypePei::class.java), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.nature</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.nature</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.nature</code> table reference
     */
    constructor() : this(DSL.name("nature"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, NATURE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class NaturePath : Nature, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): NaturePath = NaturePath(DSL.name(alias), this)
        override fun `as`(alias: Name): NaturePath = NaturePath(alias, this)
        override fun `as`(alias: Table<*>): NaturePath = NaturePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = NATURE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(NATURE_NATURE_CODE_KEY)

    private lateinit var _lDiametreNature: LDiametreNaturePath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.l_diametre_nature</code> table
     */
    fun lDiametreNature(): LDiametreNaturePath {
        if (!this::_lDiametreNature.isInitialized) {
            _lDiametreNature = LDiametreNaturePath(this, null, L_DIAMETRE_NATURE__L_DIAMETRE_NATURE_NATURE_ID_FKEY.inverseKey)
        }

        return _lDiametreNature
    }

    val lDiametreNature: LDiametreNaturePath
        get(): LDiametreNaturePath = lDiametreNature()

    private lateinit var _pei: PeiPath

    /**
     * Get the implicit to-many join path to the <code>remocra.pei</code> table
     */
    fun pei(): PeiPath {
        if (!this::_pei.isInitialized) {
            _pei = PeiPath(this, null, PEI__PEI_PEI_NATURE_ID_FKEY.inverseKey)
        }

        return _pei
    }

    val pei: PeiPath
        get(): PeiPath = pei()

    private lateinit var _poidsAnomalie: PoidsAnomaliePath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.poids_anomalie</code> table
     */
    fun poidsAnomalie(): PoidsAnomaliePath {
        if (!this::_poidsAnomalie.isInitialized) {
            _poidsAnomalie = PoidsAnomaliePath(this, null, POIDS_ANOMALIE__POIDS_ANOMALIE_POIDS_ANOMALIE_NATURE_ID_FKEY.inverseKey)
        }

        return _poidsAnomalie
    }

    val poidsAnomalie: PoidsAnomaliePath
        get(): PoidsAnomaliePath = poidsAnomalie()

    /**
     * Get the implicit many-to-many join path to the
     * <code>remocra.diametre</code> table
     */
    val diametre: DiametrePath
        get(): DiametrePath = lDiametreNature().diametre()

    /**
     * Get the implicit many-to-many join path to the
     * <code>remocra.anomalie</code> table
     */
    val anomalie: AnomaliePath
        get(): AnomaliePath = poidsAnomalie().anomalie()
    override fun `as`(alias: String): Nature = Nature(DSL.name(alias), this)
    override fun `as`(alias: Name): Nature = Nature(alias, this)
    override fun `as`(alias: Table<*>): Nature = Nature(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Nature = Nature(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Nature = Nature(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Nature = Nature(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Nature = Nature(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Nature = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Nature = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Nature = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Nature = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Nature = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Nature = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Nature = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Nature = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Nature = where(DSL.notExists(select))
}
