/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.OLDEB_TYPE_DEBROUSSAILLEMENT_OLDEB_TYPE_DEBROUSSAILLEMENT_C_KEY
import remocra.db.jooq.remocra.keys.OLDEB_TYPE_DEBROUSSAILLEMENT_PKEY
import remocra.db.jooq.remocra.keys.OLDEB_VISITE__OLDEB_VISITE_OLDEB_VISITE_DEBROUSSAILLEMENT_ACCES_ID_FKEY
import remocra.db.jooq.remocra.keys.OLDEB_VISITE__OLDEB_VISITE_OLDEB_VISITE_DEBROUSSAILLEMENT_PARCELLE_ID_FKEY
import remocra.db.jooq.remocra.tables.OldebVisite.OldebVisitePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class OldebTypeDebroussaillement(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>remocra.oldeb_type_debroussaillement</code>
         */
        val OLDEB_TYPE_DEBROUSSAILLEMENT: OldebTypeDebroussaillement = OldebTypeDebroussaillement()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column
     * <code>remocra.oldeb_type_debroussaillement.oldeb_type_debroussaillement_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("oldeb_type_debroussaillement_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_type_debroussaillement.oldeb_type_debroussaillement_actif</code>.
     */
    val ACTIF: TableField<Record, Boolean?> = createField(DSL.name("oldeb_type_debroussaillement_actif"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_type_debroussaillement.oldeb_type_debroussaillement_code</code>.
     */
    val CODE: TableField<Record, String?> = createField(DSL.name("oldeb_type_debroussaillement_code"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_type_debroussaillement.oldeb_type_debroussaillement_libelle</code>.
     */
    val LIBELLE: TableField<Record, String?> = createField(DSL.name("oldeb_type_debroussaillement_libelle"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.oldeb_type_debroussaillement</code> table
     * reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.oldeb_type_debroussaillement</code> table
     * reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.oldeb_type_debroussaillement</code> table
     * reference
     */
    constructor() : this(DSL.name("oldeb_type_debroussaillement"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, OLDEB_TYPE_DEBROUSSAILLEMENT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = [
            "https://www.jooq.org",
            "jOOQ version:3.20.10",
        ],
        comments = "This class is generated by jOOQ",
    )
    open class OldebTypeDebroussaillementPath : OldebTypeDebroussaillement, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): OldebTypeDebroussaillementPath = OldebTypeDebroussaillementPath(DSL.name(alias), this)
        override fun `as`(alias: Name): OldebTypeDebroussaillementPath = OldebTypeDebroussaillementPath(alias, this)
        override fun `as`(alias: Table<*>): OldebTypeDebroussaillementPath = OldebTypeDebroussaillementPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = OLDEB_TYPE_DEBROUSSAILLEMENT_PKEY
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(OLDEB_TYPE_DEBROUSSAILLEMENT_OLDEB_TYPE_DEBROUSSAILLEMENT_C_KEY)

    private lateinit var _oldebVisiteOldebVisiteDebroussaillementAccesIdFkey: OldebVisitePath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.oldeb_visite</code> table, via the
     * <code>oldeb_visite_oldeb_visite_debroussaillement_acces_id_fkey</code>
     * key
     */
    fun oldebVisiteOldebVisiteDebroussaillementAccesIdFkey(): OldebVisitePath {
        if (!this::_oldebVisiteOldebVisiteDebroussaillementAccesIdFkey.isInitialized) {
            _oldebVisiteOldebVisiteDebroussaillementAccesIdFkey = OldebVisitePath(this, null, OLDEB_VISITE__OLDEB_VISITE_OLDEB_VISITE_DEBROUSSAILLEMENT_ACCES_ID_FKEY.inverseKey)
        }

        return _oldebVisiteOldebVisiteDebroussaillementAccesIdFkey
    }

    val oldebVisiteOldebVisiteDebroussaillementAccesIdFkey: OldebVisitePath
        get(): OldebVisitePath = oldebVisiteOldebVisiteDebroussaillementAccesIdFkey()

    private lateinit var _oldebVisiteOldebVisiteDebroussaillementParcelleIdFkey: OldebVisitePath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.oldeb_visite</code> table, via the
     * <code>oldeb_visite_oldeb_visite_debroussaillement_parcelle_id_fkey</code>
     * key
     */
    fun oldebVisiteOldebVisiteDebroussaillementParcelleIdFkey(): OldebVisitePath {
        if (!this::_oldebVisiteOldebVisiteDebroussaillementParcelleIdFkey.isInitialized) {
            _oldebVisiteOldebVisiteDebroussaillementParcelleIdFkey = OldebVisitePath(this, null, OLDEB_VISITE__OLDEB_VISITE_OLDEB_VISITE_DEBROUSSAILLEMENT_PARCELLE_ID_FKEY.inverseKey)
        }

        return _oldebVisiteOldebVisiteDebroussaillementParcelleIdFkey
    }

    val oldebVisiteOldebVisiteDebroussaillementParcelleIdFkey: OldebVisitePath
        get(): OldebVisitePath = oldebVisiteOldebVisiteDebroussaillementParcelleIdFkey()
    override fun `as`(alias: String): OldebTypeDebroussaillement = OldebTypeDebroussaillement(DSL.name(alias), this)
    override fun `as`(alias: Name): OldebTypeDebroussaillement = OldebTypeDebroussaillement(alias, this)
    override fun `as`(alias: Table<*>): OldebTypeDebroussaillement = OldebTypeDebroussaillement(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): OldebTypeDebroussaillement = OldebTypeDebroussaillement(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): OldebTypeDebroussaillement = OldebTypeDebroussaillement(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): OldebTypeDebroussaillement = OldebTypeDebroussaillement(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): OldebTypeDebroussaillement = OldebTypeDebroussaillement(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): OldebTypeDebroussaillement = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): OldebTypeDebroussaillement = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): OldebTypeDebroussaillement = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): OldebTypeDebroussaillement = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): OldebTypeDebroussaillement = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): OldebTypeDebroussaillement = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): OldebTypeDebroussaillement = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): OldebTypeDebroussaillement = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): OldebTypeDebroussaillement = where(DSL.notExists(select))
}
