/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.enums.TypeCivilite
import remocra.db.jooq.remocra.keys.OLDEB_PROPRIETAIRE_PKEY
import remocra.db.jooq.remocra.keys.OLDEB_PROPRIETE__OLDEB_PROPRIETE_OLDEB_PROPRIETE_OLDEB_PROPRIETAIRE_ID_FKEY
import remocra.db.jooq.remocra.tables.OldebPropriete.OldebProprietePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class OldebProprietaire(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.oldeb_proprietaire</code>
         */
        val OLDEB_PROPRIETAIRE: OldebProprietaire = OldebProprietaire()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.oldeb_proprietaire.oldeb_proprietaire_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("oldeb_proprietaire_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_organisme</code>.
     */
    val ORGANISME: TableField<Record, Boolean?> = createField(DSL.name("oldeb_proprietaire_organisme"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_raison_sociale</code>.
     */
    val RAISON_SOCIALE: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_raison_sociale"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_civilite</code>.
     */
    val CIVILITE: TableField<Record, TypeCivilite?> = createField(DSL.name("oldeb_proprietaire_civilite"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(TypeCivilite::class.java), this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_nom</code>.
     */
    val NOM: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_nom"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_prenom</code>.
     */
    val PRENOM: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_prenom"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_telephone</code>.
     */
    val TELEPHONE: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_telephone"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_email</code>.
     */
    val EMAIL: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_email"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_num_voie</code>.
     */
    val NUM_VOIE: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_num_voie"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_voie</code>.
     */
    val VOIE: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_voie"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_lieu_dit</code>.
     */
    val LIEU_DIT: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_lieu_dit"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_code_postal</code>.
     */
    val CODE_POSTAL: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_code_postal"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_ville</code>.
     */
    val VILLE: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_ville"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_proprietaire.oldeb_proprietaire_pays</code>.
     */
    val PAYS: TableField<Record, String?> = createField(DSL.name("oldeb_proprietaire_pays"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.oldeb_proprietaire</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.oldeb_proprietaire</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.oldeb_proprietaire</code> table reference
     */
    constructor() : this(DSL.name("oldeb_proprietaire"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, OLDEB_PROPRIETAIRE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class OldebProprietairePath : OldebProprietaire, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): OldebProprietairePath = OldebProprietairePath(DSL.name(alias), this)
        override fun `as`(alias: Name): OldebProprietairePath = OldebProprietairePath(alias, this)
        override fun `as`(alias: Table<*>): OldebProprietairePath = OldebProprietairePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = OLDEB_PROPRIETAIRE_PKEY

    private lateinit var _oldebPropriete: OldebProprietePath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.oldeb_propriete</code> table
     */
    fun oldebPropriete(): OldebProprietePath {
        if (!this::_oldebPropriete.isInitialized) {
            _oldebPropriete = OldebProprietePath(this, null, OLDEB_PROPRIETE__OLDEB_PROPRIETE_OLDEB_PROPRIETE_OLDEB_PROPRIETAIRE_ID_FKEY.inverseKey)
        }

        return _oldebPropriete
    }

    val oldebPropriete: OldebProprietePath
        get(): OldebProprietePath = oldebPropriete()
    override fun `as`(alias: String): OldebProprietaire = OldebProprietaire(DSL.name(alias), this)
    override fun `as`(alias: Name): OldebProprietaire = OldebProprietaire(alias, this)
    override fun `as`(alias: Table<*>): OldebProprietaire = OldebProprietaire(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): OldebProprietaire = OldebProprietaire(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): OldebProprietaire = OldebProprietaire(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): OldebProprietaire = OldebProprietaire(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): OldebProprietaire = OldebProprietaire(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): OldebProprietaire = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): OldebProprietaire = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): OldebProprietaire = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): OldebProprietaire = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): OldebProprietaire = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): OldebProprietaire = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): OldebProprietaire = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): OldebProprietaire = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): OldebProprietaire = where(DSL.notExists(select))
}
