/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.OLDEB_PROPRIETE__OLDEB_PROPRIETE_OLDEB_PROPRIETE_OLDEB_TYPE_RESIDENCE_ID_FKEY
import remocra.db.jooq.remocra.keys.OLDEB_TYPE_RESIDENCE_OLDEB_TYPE_RESIDENCE_CODE_KEY
import remocra.db.jooq.remocra.keys.OLDEB_TYPE_RESIDENCE_PKEY
import remocra.db.jooq.remocra.tables.OldebPropriete.OldebProprietePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class OldebTypeResidence(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.oldeb_type_residence</code>
         */
        val OLDEB_TYPE_RESIDENCE: OldebTypeResidence = OldebTypeResidence()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column
     * <code>remocra.oldeb_type_residence.oldeb_type_residence_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("oldeb_type_residence_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_type_residence.oldeb_type_residence_actif</code>.
     */
    val ACTIF: TableField<Record, Boolean?> = createField(DSL.name("oldeb_type_residence_actif"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_type_residence.oldeb_type_residence_code</code>.
     */
    val CODE: TableField<Record, String?> = createField(DSL.name("oldeb_type_residence_code"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_type_residence.oldeb_type_residence_libelle</code>.
     */
    val LIBELLE: TableField<Record, String?> = createField(DSL.name("oldeb_type_residence_libelle"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.oldeb_type_residence</code> table
     * reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.oldeb_type_residence</code> table
     * reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.oldeb_type_residence</code> table reference
     */
    constructor() : this(DSL.name("oldeb_type_residence"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, OLDEB_TYPE_RESIDENCE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class OldebTypeResidencePath : OldebTypeResidence, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): OldebTypeResidencePath = OldebTypeResidencePath(DSL.name(alias), this)
        override fun `as`(alias: Name): OldebTypeResidencePath = OldebTypeResidencePath(alias, this)
        override fun `as`(alias: Table<*>): OldebTypeResidencePath = OldebTypeResidencePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = OLDEB_TYPE_RESIDENCE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(OLDEB_TYPE_RESIDENCE_OLDEB_TYPE_RESIDENCE_CODE_KEY)

    private lateinit var _oldebPropriete: OldebProprietePath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.oldeb_propriete</code> table
     */
    fun oldebPropriete(): OldebProprietePath {
        if (!this::_oldebPropriete.isInitialized) {
            _oldebPropriete = OldebProprietePath(this, null, OLDEB_PROPRIETE__OLDEB_PROPRIETE_OLDEB_PROPRIETE_OLDEB_TYPE_RESIDENCE_ID_FKEY.inverseKey)
        }

        return _oldebPropriete
    }

    val oldebPropriete: OldebProprietePath
        get(): OldebProprietePath = oldebPropriete()
    override fun `as`(alias: String): OldebTypeResidence = OldebTypeResidence(DSL.name(alias), this)
    override fun `as`(alias: Name): OldebTypeResidence = OldebTypeResidence(alias, this)
    override fun `as`(alias: Table<*>): OldebTypeResidence = OldebTypeResidence(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): OldebTypeResidence = OldebTypeResidence(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): OldebTypeResidence = OldebTypeResidence(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): OldebTypeResidence = OldebTypeResidence(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): OldebTypeResidence = OldebTypeResidence(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): OldebTypeResidence = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): OldebTypeResidence = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): OldebTypeResidence = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): OldebTypeResidence = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): OldebTypeResidence = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): OldebTypeResidence = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): OldebTypeResidence = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): OldebTypeResidence = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): OldebTypeResidence = where(DSL.notExists(select))
}
