/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.bindings.ZonedDateTimeBinding
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.OLDEB_VISITE_SUITE_PKEY
import remocra.db.jooq.remocra.keys.OLDEB_VISITE_SUITE__OLDEB_VISITE_SUITE_OLDEB_VISITE_SUITE_OLDEB_TYPE_SUITE_ID_FKEY
import remocra.db.jooq.remocra.keys.OLDEB_VISITE_SUITE__OLDEB_VISITE_SUITE_OLDEB_VISITE_SUITE_OLDEB_VISITE_ID_FKEY
import remocra.db.jooq.remocra.tables.OldebTypeSuite.OldebTypeSuitePath
import remocra.db.jooq.remocra.tables.OldebVisite.OldebVisitePath
import java.time.ZonedDateTime
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.9",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class OldebVisiteSuite(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.oldeb_visite_suite</code>
         */
        val OLDEB_VISITE_SUITE: OldebVisiteSuite = OldebVisiteSuite()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.oldeb_visite_suite.oldeb_visite_suite_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("oldeb_visite_suite_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_visite_suite.oldeb_visite_suite_oldeb_visite_id</code>.
     */
    val OLDEB_VISITE_ID: TableField<Record, UUID?> = createField(DSL.name("oldeb_visite_suite_oldeb_visite_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_visite_suite.oldeb_visite_suite_oldeb_type_suite_id</code>.
     */
    val OLDEB_TYPE_SUITE_ID: TableField<Record, UUID?> = createField(DSL.name("oldeb_visite_suite_oldeb_type_suite_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_visite_suite.oldeb_visite_suite_date</code>.
     */
    val DATE: TableField<Record, ZonedDateTime?> = createField(DSL.name("oldeb_visite_suite_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", ZonedDateTimeBinding())

    /**
     * The column
     * <code>remocra.oldeb_visite_suite.oldeb_visite_suite_observation</code>.
     */
    val OBSERVATION: TableField<Record, String?> = createField(DSL.name("oldeb_visite_suite_observation"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.oldeb_visite_suite</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.oldeb_visite_suite</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.oldeb_visite_suite</code> table reference
     */
    constructor() : this(DSL.name("oldeb_visite_suite"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, OLDEB_VISITE_SUITE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = [
            "https://www.jooq.org",
            "jOOQ version:3.20.9",
        ],
        comments = "This class is generated by jOOQ",
    )
    open class OldebVisiteSuitePath : OldebVisiteSuite, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): OldebVisiteSuitePath = OldebVisiteSuitePath(DSL.name(alias), this)
        override fun `as`(alias: Name): OldebVisiteSuitePath = OldebVisiteSuitePath(alias, this)
        override fun `as`(alias: Table<*>): OldebVisiteSuitePath = OldebVisiteSuitePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = OLDEB_VISITE_SUITE_PKEY
    override fun getReferences(): List<ForeignKey<Record, *>> = listOf(OLDEB_VISITE_SUITE__OLDEB_VISITE_SUITE_OLDEB_VISITE_SUITE_OLDEB_TYPE_SUITE_ID_FKEY, OLDEB_VISITE_SUITE__OLDEB_VISITE_SUITE_OLDEB_VISITE_SUITE_OLDEB_VISITE_ID_FKEY)

    /**
     * Get the implicit join path to the <code>remocra.oldeb_type_suite</code>
     * table.
     */
    fun oldebTypeSuite(): OldebTypeSuitePath = oldebTypeSuite
    val oldebTypeSuite: OldebTypeSuitePath by lazy { OldebTypeSuitePath(this, OLDEB_VISITE_SUITE__OLDEB_VISITE_SUITE_OLDEB_VISITE_SUITE_OLDEB_TYPE_SUITE_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>remocra.oldeb_visite</code>
     * table.
     */
    fun oldebVisite(): OldebVisitePath = oldebVisite
    val oldebVisite: OldebVisitePath by lazy { OldebVisitePath(this, OLDEB_VISITE_SUITE__OLDEB_VISITE_SUITE_OLDEB_VISITE_SUITE_OLDEB_VISITE_ID_FKEY, null) }
    override fun `as`(alias: String): OldebVisiteSuite = OldebVisiteSuite(DSL.name(alias), this)
    override fun `as`(alias: Name): OldebVisiteSuite = OldebVisiteSuite(alias, this)
    override fun `as`(alias: Table<*>): OldebVisiteSuite = OldebVisiteSuite(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): OldebVisiteSuite = OldebVisiteSuite(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): OldebVisiteSuite = OldebVisiteSuite(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): OldebVisiteSuite = OldebVisiteSuite(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): OldebVisiteSuite = OldebVisiteSuite(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): OldebVisiteSuite = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): OldebVisiteSuite = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): OldebVisiteSuite = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): OldebVisiteSuite = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): OldebVisiteSuite = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): OldebVisiteSuite = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): OldebVisiteSuite = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): OldebVisiteSuite = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): OldebVisiteSuite = where(DSL.notExists(select))
}
