/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.OLDEB_TYPE_SUITE_OLDEB_TYPE_SUITE_CODE_KEY
import remocra.db.jooq.remocra.keys.OLDEB_TYPE_SUITE_PKEY
import remocra.db.jooq.remocra.keys.OLDEB_VISITE_SUITE__OLDEB_VISITE_SUITE_OLDEB_VISITE_SUITE_OLDEB_TYPE_SUITE_ID_FKEY
import remocra.db.jooq.remocra.tables.OldebVisiteSuite.OldebVisiteSuitePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class OldebTypeSuite(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.oldeb_type_suite</code>
         */
        val OLDEB_TYPE_SUITE: OldebTypeSuite = OldebTypeSuite()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.oldeb_type_suite.oldeb_type_suite_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("oldeb_type_suite_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>remocra.oldeb_type_suite.oldeb_type_suite_actif</code>.
     */
    val ACTIF: TableField<Record, Boolean?> = createField(DSL.name("oldeb_type_suite_actif"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>remocra.oldeb_type_suite.oldeb_type_suite_code</code>.
     */
    val CODE: TableField<Record, String?> = createField(DSL.name("oldeb_type_suite_code"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>remocra.oldeb_type_suite.oldeb_type_suite_libelle</code>.
     */
    val LIBELLE: TableField<Record, String?> = createField(DSL.name("oldeb_type_suite_libelle"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.oldeb_type_suite</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.oldeb_type_suite</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.oldeb_type_suite</code> table reference
     */
    constructor() : this(DSL.name("oldeb_type_suite"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, OLDEB_TYPE_SUITE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class OldebTypeSuitePath : OldebTypeSuite, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): OldebTypeSuitePath = OldebTypeSuitePath(DSL.name(alias), this)
        override fun `as`(alias: Name): OldebTypeSuitePath = OldebTypeSuitePath(alias, this)
        override fun `as`(alias: Table<*>): OldebTypeSuitePath = OldebTypeSuitePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = OLDEB_TYPE_SUITE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(OLDEB_TYPE_SUITE_OLDEB_TYPE_SUITE_CODE_KEY)

    private lateinit var _oldebVisiteSuite: OldebVisiteSuitePath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.oldeb_visite_suite</code> table
     */
    fun oldebVisiteSuite(): OldebVisiteSuitePath {
        if (!this::_oldebVisiteSuite.isInitialized) {
            _oldebVisiteSuite = OldebVisiteSuitePath(this, null, OLDEB_VISITE_SUITE__OLDEB_VISITE_SUITE_OLDEB_VISITE_SUITE_OLDEB_TYPE_SUITE_ID_FKEY.inverseKey)
        }

        return _oldebVisiteSuite
    }

    val oldebVisiteSuite: OldebVisiteSuitePath
        get(): OldebVisiteSuitePath = oldebVisiteSuite()
    override fun `as`(alias: String): OldebTypeSuite = OldebTypeSuite(DSL.name(alias), this)
    override fun `as`(alias: Name): OldebTypeSuite = OldebTypeSuite(alias, this)
    override fun `as`(alias: Table<*>): OldebTypeSuite = OldebTypeSuite(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): OldebTypeSuite = OldebTypeSuite(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): OldebTypeSuite = OldebTypeSuite(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): OldebTypeSuite = OldebTypeSuite(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): OldebTypeSuite = OldebTypeSuite(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): OldebTypeSuite = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): OldebTypeSuite = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): OldebTypeSuite = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): OldebTypeSuite = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): OldebTypeSuite = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): OldebTypeSuite = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): OldebTypeSuite = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): OldebTypeSuite = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): OldebTypeSuite = where(DSL.notExists(select))
}
