/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.remocra.Remocra
import remocra.db.jooq.remocra.keys.EVENEMENT__EVENEMENT_UTILISATEUR_ID_FKEY
import remocra.db.jooq.remocra.keys.JOB__JOB_JOB_UTILISATEUR_ID_FKEY
import remocra.db.jooq.remocra.keys.L_COURRIER_UTILISATEUR__L_COURRIER_UTILISATEUR_UTILISATEUR_ID_FKEY
import remocra.db.jooq.remocra.keys.MESSAGE_EVENEMENT__MESSAGE_EVENEMENT_UTILISATEUR_ID_FKEY
import remocra.db.jooq.remocra.keys.PERMIS__PERMIS_PERMIS_INSTRUCTEUR_ID_FKEY
import remocra.db.jooq.remocra.keys.RCCI__RCCI_RCCI_RCCI_ARRIVEE_DDTM_ONF_ID_FKEY
import remocra.db.jooq.remocra.keys.RCCI__RCCI_RCCI_RCCI_ARRIVEE_GENDARMERIE_ID_FKEY
import remocra.db.jooq.remocra.keys.RCCI__RCCI_RCCI_RCCI_ARRIVEE_POLICE_ID_FKEY
import remocra.db.jooq.remocra.keys.RCCI__RCCI_RCCI_RCCI_ARRIVEE_SDIS_ID_FKEY
import remocra.db.jooq.remocra.keys.RCCI__RCCI_RCCI_UTILISATEUR_ID_FKEY
import remocra.db.jooq.remocra.keys.SIGNALEMENT__SIGNALEMENT_SIGNALEMENT_UTILISATEUR_FKEY
import remocra.db.jooq.remocra.keys.TOURNEE__TOURNEE_TOURNEE_RESERVATION_UTILISATEUR_ID_FKEY
import remocra.db.jooq.remocra.keys.UTILISATEUR_PKEY
import remocra.db.jooq.remocra.keys.UTILISATEUR_UTILISATEUR_EMAIL_KEY
import remocra.db.jooq.remocra.keys.UTILISATEUR_UTILISATEUR_USERNAME_KEY
import remocra.db.jooq.remocra.keys.UTILISATEUR__UTILISATEUR_UTILISATEUR_ORGANISME_ID_FKEY
import remocra.db.jooq.remocra.keys.UTILISATEUR__UTILISATEUR_UTILISATEUR_PROFIL_UTILISATEUR_ID_FKEY
import remocra.db.jooq.remocra.tables.Courrier.CourrierPath
import remocra.db.jooq.remocra.tables.Evenement.EvenementPath
import remocra.db.jooq.remocra.tables.Job.JobPath
import remocra.db.jooq.remocra.tables.LCourrierUtilisateur.LCourrierUtilisateurPath
import remocra.db.jooq.remocra.tables.MessageEvenement.MessageEvenementPath
import remocra.db.jooq.remocra.tables.Organisme.OrganismePath
import remocra.db.jooq.remocra.tables.Permis.PermisPath
import remocra.db.jooq.remocra.tables.ProfilUtilisateur.ProfilUtilisateurPath
import remocra.db.jooq.remocra.tables.Rcci.RcciPath
import remocra.db.jooq.remocra.tables.Signalement.SignalementPath
import remocra.db.jooq.remocra.tables.Tournee.TourneePath
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class Utilisateur(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Remocra.REMOCRA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>remocra.utilisateur</code>
         */
        val UTILISATEUR: Utilisateur = Utilisateur()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>remocra.utilisateur.utilisateur_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("utilisateur_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_actif</code>.
     */
    val ACTIF: TableField<Record, Boolean?> = createField(DSL.name("utilisateur_actif"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_email</code>.
     */
    val EMAIL: TableField<Record, String?> = createField(DSL.name("utilisateur_email"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_nom</code>.
     */
    val NOM: TableField<Record, String?> = createField(DSL.name("utilisateur_nom"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_prenom</code>.
     */
    val PRENOM: TableField<Record, String?> = createField(DSL.name("utilisateur_prenom"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_username</code>.
     */
    val USERNAME: TableField<Record, String?> = createField(DSL.name("utilisateur_username"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_telephone</code>.
     */
    val TELEPHONE: TableField<Record, String?> = createField(DSL.name("utilisateur_telephone"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_can_be_notified</code>.
     */
    val CAN_BE_NOTIFIED: TableField<Record, Boolean?> = createField(DSL.name("utilisateur_can_be_notified"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column
     * <code>remocra.utilisateur.utilisateur_profil_utilisateur_id</code>.
     */
    val PROFIL_UTILISATEUR_ID: TableField<Record, UUID?> = createField(DSL.name("utilisateur_profil_utilisateur_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_organisme_id</code>.
     */
    val ORGANISME_ID: TableField<Record, UUID?> = createField(DSL.name("utilisateur_organisme_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>remocra.utilisateur.utilisateur_is_super_admin</code>.
     */
    val IS_SUPER_ADMIN: TableField<Record, Boolean?> = createField(DSL.name("utilisateur_is_super_admin"), SQLDataType.BOOLEAN, this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>remocra.utilisateur</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>remocra.utilisateur</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>remocra.utilisateur</code> table reference
     */
    constructor() : this(DSL.name("utilisateur"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, UTILISATEUR, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UtilisateurPath : Utilisateur, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): UtilisateurPath = UtilisateurPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UtilisateurPath = UtilisateurPath(alias, this)
        override fun `as`(alias: Table<*>): UtilisateurPath = UtilisateurPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Remocra.REMOCRA
    override fun getPrimaryKey(): UniqueKey<Record> = UTILISATEUR_PKEY
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(UTILISATEUR_UTILISATEUR_EMAIL_KEY, UTILISATEUR_UTILISATEUR_USERNAME_KEY)
    override fun getReferences(): List<ForeignKey<Record, *>> = listOf(UTILISATEUR__UTILISATEUR_UTILISATEUR_ORGANISME_ID_FKEY, UTILISATEUR__UTILISATEUR_UTILISATEUR_PROFIL_UTILISATEUR_ID_FKEY)

    private lateinit var _organisme: OrganismePath

    /**
     * Get the implicit join path to the <code>remocra.organisme</code> table.
     */
    fun organisme(): OrganismePath {
        if (!this::_organisme.isInitialized) {
            _organisme = OrganismePath(this, UTILISATEUR__UTILISATEUR_UTILISATEUR_ORGANISME_ID_FKEY, null)
        }

        return _organisme
    }

    val organisme: OrganismePath
        get(): OrganismePath = organisme()

    private lateinit var _profilUtilisateur: ProfilUtilisateurPath

    /**
     * Get the implicit join path to the <code>remocra.profil_utilisateur</code>
     * table.
     */
    fun profilUtilisateur(): ProfilUtilisateurPath {
        if (!this::_profilUtilisateur.isInitialized) {
            _profilUtilisateur = ProfilUtilisateurPath(this, UTILISATEUR__UTILISATEUR_UTILISATEUR_PROFIL_UTILISATEUR_ID_FKEY, null)
        }

        return _profilUtilisateur
    }

    val profilUtilisateur: ProfilUtilisateurPath
        get(): ProfilUtilisateurPath = profilUtilisateur()

    private lateinit var _evenement: EvenementPath

    /**
     * Get the implicit to-many join path to the <code>remocra.evenement</code>
     * table
     */
    fun evenement(): EvenementPath {
        if (!this::_evenement.isInitialized) {
            _evenement = EvenementPath(this, null, EVENEMENT__EVENEMENT_UTILISATEUR_ID_FKEY.inverseKey)
        }

        return _evenement
    }

    val evenement: EvenementPath
        get(): EvenementPath = evenement()

    private lateinit var _job: JobPath

    /**
     * Get the implicit to-many join path to the <code>remocra.job</code> table
     */
    fun job(): JobPath {
        if (!this::_job.isInitialized) {
            _job = JobPath(this, null, JOB__JOB_JOB_UTILISATEUR_ID_FKEY.inverseKey)
        }

        return _job
    }

    val job: JobPath
        get(): JobPath = job()

    private lateinit var _lCourrierUtilisateur: LCourrierUtilisateurPath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.l_courrier_utilisateur</code> table
     */
    fun lCourrierUtilisateur(): LCourrierUtilisateurPath {
        if (!this::_lCourrierUtilisateur.isInitialized) {
            _lCourrierUtilisateur = LCourrierUtilisateurPath(this, null, L_COURRIER_UTILISATEUR__L_COURRIER_UTILISATEUR_UTILISATEUR_ID_FKEY.inverseKey)
        }

        return _lCourrierUtilisateur
    }

    val lCourrierUtilisateur: LCourrierUtilisateurPath
        get(): LCourrierUtilisateurPath = lCourrierUtilisateur()

    private lateinit var _messageEvenement: MessageEvenementPath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.message_evenement</code> table
     */
    fun messageEvenement(): MessageEvenementPath {
        if (!this::_messageEvenement.isInitialized) {
            _messageEvenement = MessageEvenementPath(this, null, MESSAGE_EVENEMENT__MESSAGE_EVENEMENT_UTILISATEUR_ID_FKEY.inverseKey)
        }

        return _messageEvenement
    }

    val messageEvenement: MessageEvenementPath
        get(): MessageEvenementPath = messageEvenement()

    private lateinit var _permis: PermisPath

    /**
     * Get the implicit to-many join path to the <code>remocra.permis</code>
     * table
     */
    fun permis(): PermisPath {
        if (!this::_permis.isInitialized) {
            _permis = PermisPath(this, null, PERMIS__PERMIS_PERMIS_INSTRUCTEUR_ID_FKEY.inverseKey)
        }

        return _permis
    }

    val permis: PermisPath
        get(): PermisPath = permis()

    private lateinit var _rcciRcciRcciArriveeDdtmOnfIdFkey: RcciPath

    /**
     * Get the implicit to-many join path to the <code>remocra.rcci</code>
     * table, via the <code>rcci_rcci_rcci_arrivee_ddtm_onf_id_fkey</code> key
     */
    fun rcciRcciRcciArriveeDdtmOnfIdFkey(): RcciPath {
        if (!this::_rcciRcciRcciArriveeDdtmOnfIdFkey.isInitialized) {
            _rcciRcciRcciArriveeDdtmOnfIdFkey = RcciPath(this, null, RCCI__RCCI_RCCI_RCCI_ARRIVEE_DDTM_ONF_ID_FKEY.inverseKey)
        }

        return _rcciRcciRcciArriveeDdtmOnfIdFkey
    }

    val rcciRcciRcciArriveeDdtmOnfIdFkey: RcciPath
        get(): RcciPath = rcciRcciRcciArriveeDdtmOnfIdFkey()

    private lateinit var _rcciRcciRcciArriveeGendarmerieIdFkey: RcciPath

    /**
     * Get the implicit to-many join path to the <code>remocra.rcci</code>
     * table, via the <code>rcci_rcci_rcci_arrivee_gendarmerie_id_fkey</code>
     * key
     */
    fun rcciRcciRcciArriveeGendarmerieIdFkey(): RcciPath {
        if (!this::_rcciRcciRcciArriveeGendarmerieIdFkey.isInitialized) {
            _rcciRcciRcciArriveeGendarmerieIdFkey = RcciPath(this, null, RCCI__RCCI_RCCI_RCCI_ARRIVEE_GENDARMERIE_ID_FKEY.inverseKey)
        }

        return _rcciRcciRcciArriveeGendarmerieIdFkey
    }

    val rcciRcciRcciArriveeGendarmerieIdFkey: RcciPath
        get(): RcciPath = rcciRcciRcciArriveeGendarmerieIdFkey()

    private lateinit var _rcciRcciRcciArriveePoliceIdFkey: RcciPath

    /**
     * Get the implicit to-many join path to the <code>remocra.rcci</code>
     * table, via the <code>rcci_rcci_rcci_arrivee_police_id_fkey</code> key
     */
    fun rcciRcciRcciArriveePoliceIdFkey(): RcciPath {
        if (!this::_rcciRcciRcciArriveePoliceIdFkey.isInitialized) {
            _rcciRcciRcciArriveePoliceIdFkey = RcciPath(this, null, RCCI__RCCI_RCCI_RCCI_ARRIVEE_POLICE_ID_FKEY.inverseKey)
        }

        return _rcciRcciRcciArriveePoliceIdFkey
    }

    val rcciRcciRcciArriveePoliceIdFkey: RcciPath
        get(): RcciPath = rcciRcciRcciArriveePoliceIdFkey()

    private lateinit var _rcciRcciRcciArriveeSdisIdFkey: RcciPath

    /**
     * Get the implicit to-many join path to the <code>remocra.rcci</code>
     * table, via the <code>rcci_rcci_rcci_arrivee_sdis_id_fkey</code> key
     */
    fun rcciRcciRcciArriveeSdisIdFkey(): RcciPath {
        if (!this::_rcciRcciRcciArriveeSdisIdFkey.isInitialized) {
            _rcciRcciRcciArriveeSdisIdFkey = RcciPath(this, null, RCCI__RCCI_RCCI_RCCI_ARRIVEE_SDIS_ID_FKEY.inverseKey)
        }

        return _rcciRcciRcciArriveeSdisIdFkey
    }

    val rcciRcciRcciArriveeSdisIdFkey: RcciPath
        get(): RcciPath = rcciRcciRcciArriveeSdisIdFkey()

    private lateinit var _rcciRcciUtilisateurIdFkey: RcciPath

    /**
     * Get the implicit to-many join path to the <code>remocra.rcci</code>
     * table, via the <code>rcci_rcci_utilisateur_id_fkey</code> key
     */
    fun rcciRcciUtilisateurIdFkey(): RcciPath {
        if (!this::_rcciRcciUtilisateurIdFkey.isInitialized) {
            _rcciRcciUtilisateurIdFkey = RcciPath(this, null, RCCI__RCCI_RCCI_UTILISATEUR_ID_FKEY.inverseKey)
        }

        return _rcciRcciUtilisateurIdFkey
    }

    val rcciRcciUtilisateurIdFkey: RcciPath
        get(): RcciPath = rcciRcciUtilisateurIdFkey()

    private lateinit var _signalement: SignalementPath

    /**
     * Get the implicit to-many join path to the
     * <code>remocra.signalement</code> table
     */
    fun signalement(): SignalementPath {
        if (!this::_signalement.isInitialized) {
            _signalement = SignalementPath(this, null, SIGNALEMENT__SIGNALEMENT_SIGNALEMENT_UTILISATEUR_FKEY.inverseKey)
        }

        return _signalement
    }

    val signalement: SignalementPath
        get(): SignalementPath = signalement()

    private lateinit var _tournee: TourneePath

    /**
     * Get the implicit to-many join path to the <code>remocra.tournee</code>
     * table
     */
    fun tournee(): TourneePath {
        if (!this::_tournee.isInitialized) {
            _tournee = TourneePath(this, null, TOURNEE__TOURNEE_TOURNEE_RESERVATION_UTILISATEUR_ID_FKEY.inverseKey)
        }

        return _tournee
    }

    val tournee: TourneePath
        get(): TourneePath = tournee()

    /**
     * Get the implicit many-to-many join path to the
     * <code>remocra.courrier</code> table
     */
    val courrier: CourrierPath
        get(): CourrierPath = lCourrierUtilisateur().courrier()
    override fun `as`(alias: String): Utilisateur = Utilisateur(DSL.name(alias), this)
    override fun `as`(alias: Name): Utilisateur = Utilisateur(alias, this)
    override fun `as`(alias: Table<*>): Utilisateur = Utilisateur(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Utilisateur = Utilisateur(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Utilisateur = Utilisateur(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Utilisateur = Utilisateur(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Utilisateur = Utilisateur(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Utilisateur = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Utilisateur = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Utilisateur = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Utilisateur = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Utilisateur = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Utilisateur = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Utilisateur = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Utilisateur = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Utilisateur = where(DSL.notExists(select))
}
