-- Ajout des droits manquant
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_ZONE_COMPETENCE';
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_ANOMALIES';
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_GROUPE_UTILISATEUR';
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_COUCHE_CARTOGRAPHIQUE';
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_NOMENCLATURE';
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_ROLE_CONTACT';
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_TYPE_ETUDE';
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_COURRIER';
