-- Retirer les Foreign keys avant de modifier la table profil_droit
AlTER TABLE remocra.l_couche_droit DROP CONSTRAINT l_couche_droit_profil_droit_id_fkey;
ALTER TABLE remocra.l_modele_courrier_profil_droit DROP CONSTRAINT l_modele_courrier_profil_droit_profil_droit_id_fkey;
ALTER TABLE remocra.l_profil_droit_document_habilitable DROP CONSTRAINT l_profil_droit_document_habilitable_profil_droit_id_fkey;
ALTER TABLE remocra.l_profil_utilisateur_organisme_droit DROP CONSTRAINT l_profil_utilisateur_organisme_droit_profil_droit_id_fkey;
ALTER TABLE remocra.l_rapport_personnalise_profil_droit DROP CONSTRAINT l_rapport_personnalise_profil_droit_profil_droit_id_fkey;

--Modification de profil_droit
ALTER TABLE remocra.profil_droit RENAME TO groupe_fonctionnalites;
ALTER TABLE remocra.groupe_fonctionnalites RENAME COLUMN profil_droit_id TO groupe_fonctionnalites_id;
ALTER TABLE remocra.groupe_fonctionnalites RENAME COLUMN profil_droit_code TO groupe_fonctionnalites_code;
ALTER TABLE remocra.groupe_fonctionnalites RENAME COLUMN profil_droit_libelle TO groupe_fonctionnalites_libelle;
ALTER TABLE remocra.groupe_fonctionnalites RENAME COLUMN profil_droit_droits TO groupe_fonctionnalites_droits;
ALTER TABLE remocra.groupe_fonctionnalites RENAME COLUMN profil_droit_actif TO groupe_fonctionnalites_actif;
ALTER TABLE remocra.groupe_fonctionnalites RENAME CONSTRAINT profil_droit_pkey TO groupe_fonctionnalites_pkey;
ALTER TABLE remocra.groupe_fonctionnalites RENAME CONSTRAINT profil_droit_profil_droit_code_key TO groupe_fonctionnalites_groupe_fonctionnalites_code_key;


--Modification de l_couche_droit
ALTER TABLE remocra.l_couche_droit RENAME TO l_couche_groupe_fonctionnalites;
ALTER TABLE remocra.l_couche_groupe_fonctionnalites RENAME COLUMN profil_droit_id TO groupe_fonctionnalites_id;
ALTER TABLE remocra.l_couche_groupe_fonctionnalites ADD CONSTRAINT l_couche_groupe_fonctionnalites_groupe_fonctionnalites_id_fkey
FOREIGN KEY (groupe_fonctionnalites_id) REFERENCES remocra.groupe_fonctionnalites(groupe_fonctionnalites_id);

ALTER TABLE remocra.l_couche_groupe_fonctionnalites RENAME CONSTRAINT l_couche_droit_pkey TO l_couche_groupe_fonctionnalites_pkey;

--Modification de l_modele_courrier_profil_droit
--Drop la FK pour pouvoir la renommer
ALTER TABLE remocra.l_modele_courrier_profil_droit DROP CONSTRAINT l_modele_courrier_profil_droit_modele_courrier_id_fkey;
--Renommage
ALTER TABLE remocra.l_modele_courrier_profil_droit RENAME TO l_modele_courrier_groupe_fonctionnalites;
ALTER TABLE remocra.l_modele_courrier_groupe_fonctionnalites RENAME COLUMN profil_droit_id TO groupe_fonctionnalites_id;
--Ajout des FKS
ALTER TABLE remocra.l_modele_courrier_groupe_fonctionnalites
ADD CONSTRAINT l_modele_courrier_groupe_fonctionnalites_groupe_fonctionnalites_id_fkey
FOREIGN KEY (groupe_fonctionnalites_id) REFERENCES remocra.groupe_fonctionnalites(groupe_fonctionnalites_id);

ALTER TABLE remocra.l_modele_courrier_groupe_fonctionnalites
ADD CONSTRAINT l_modele_courrier_groupe_fonctionnalites_modele_courrier_id_fkey
FOREIGN KEY (modele_courrier_id) REFERENCES remocra.modele_courrier(modele_courrier_id);

ALTER TABLE remocra.l_modele_courrier_groupe_fonctionnalites RENAME CONSTRAINT l_modele_courrier_profil_droit_pkey TO l_modele_courrier_groupe_fonctionnalites_pkey;

--Modification de l_profil_droit_document_habilitable
--Drop la FK pour pouvoir la renommer
ALTER TABLE remocra.l_profil_droit_document_habilitable DROP CONSTRAINT l_profil_droit_document_habilitabl_document_habilitable_id_fkey;
--Renommage
ALTER TABLE remocra.l_profil_droit_document_habilitable RENAME TO l_groupe_fonctionnalites_document_habilitable;
ALTER TABLE remocra.l_groupe_fonctionnalites_document_habilitable RENAME COLUMN profil_droit_id TO groupe_fonctionnalites_id;
--Ajout des FKS
ALTER TABLE remocra.l_groupe_fonctionnalites_document_habilitable
ADD CONSTRAINT l_groupe_fonctionnalites_document_habilitable_groupe_fonctionnalites_id_fkey
FOREIGN KEY (groupe_fonctionnalites_id) REFERENCES remocra.groupe_fonctionnalites(groupe_fonctionnalites_id);

ALTER TABLE remocra.l_groupe_fonctionnalites_document_habilitable
ADD CONSTRAINT l_groupe_fonctionnalites_document_habilitable_document_habilitable_id_fkey
FOREIGN KEY (document_habilitable_id) REFERENCES remocra.document_habilitable(document_habilitable_id);

ALTER TABLE remocra.l_groupe_fonctionnalites_document_habilitable RENAME CONSTRAINT l_profil_droit_document_habilitable_pkey TO l_groupe_fonctionnalites_document_habilitable_pkey;


--Modification de l_profil_utilisateur_organisme_droit
--Drop les FK pour pouvoir la renommer
ALTER TABLE remocra.l_profil_utilisateur_organisme_droit DROP CONSTRAINT l_profil_utilisateur_organisme_droit_profil_organisme_id_fkey;
ALTER TABLE remocra.l_profil_utilisateur_organisme_droit DROP CONSTRAINT l_profil_utilisateur_organisme_droit_profil_utilisateur_id_fkey;
--Renommage
ALTER TABLE remocra.l_profil_utilisateur_organisme_droit RENAME TO l_profil_utilisateur_organisme_groupe_fonctionnalites;
ALTER TABLE remocra.l_profil_utilisateur_organisme_groupe_fonctionnalites RENAME COLUMN profil_droit_id TO groupe_fonctionnalites_id;
--Ajout des FKS
ALTER TABLE remocra.l_profil_utilisateur_organisme_groupe_fonctionnalites
ADD CONSTRAINT l_profil_utilisateur_organisme_groupe_fonctionnalites_groupe_fonctionnalites_id_fkey
FOREIGN KEY (groupe_fonctionnalites_id) REFERENCES remocra.groupe_fonctionnalites(groupe_fonctionnalites_id);

ALTER TABLE remocra.l_profil_utilisateur_organisme_groupe_fonctionnalites
ADD CONSTRAINT l_profil_utilisateur_organisme_groupe_fonctionnalites_profil_organisme_id_fkey
FOREIGN KEY (profil_organisme_id) REFERENCES remocra.profil_organisme(profil_organisme_id);

ALTER TABLE remocra.l_profil_utilisateur_organisme_groupe_fonctionnalites
ADD CONSTRAINT l_profil_utilisateur_organisme_groupe_fonctionnalites_profil_utilisateur_id_fkey
FOREIGN KEY (profil_utilisateur_id) REFERENCES remocra.profil_utilisateur(profil_utilisateur_id);

ALTER TABLE remocra.l_profil_utilisateur_organisme_groupe_fonctionnalites RENAME CONSTRAINT l_profil_utilisateur_organisme_droit_pkey TO l_profil_utilisateur_organisme_groupe_fonctionnalites_pkey;

--Modification de l_rapport_personnalise_profil_droit
--Drop la FK pour pouvoir la renommer
ALTER TABLE remocra.l_rapport_personnalise_profil_droit DROP CONSTRAINT l_rapport_personnalise_profil_droi_rapport_personnalise_id_fkey;
--Renommage
ALTER TABLE remocra.l_rapport_personnalise_profil_droit RENAME TO l_rapport_personnalise_groupe_fonctionnalites;
ALTER TABLE remocra.l_rapport_personnalise_groupe_fonctionnalites RENAME COLUMN profil_droit_id TO groupe_fonctionnalites_id;
--Ajout des FKS
ALTER TABLE remocra.l_rapport_personnalise_groupe_fonctionnalites
ADD CONSTRAINT l_rapport_personnalise_groupe_fonctionnalites_groupe_fonctionnalites_id_fkey
FOREIGN KEY (groupe_fonctionnalites_id) REFERENCES remocra.groupe_fonctionnalites(groupe_fonctionnalites_id);

ALTER TABLE remocra.l_rapport_personnalise_groupe_fonctionnalites
ADD CONSTRAINT l_rapport_personnalise_groupe_fonctionnalites_rapport_personnalise_id_fkey
FOREIGN KEY (rapport_personnalise_id) REFERENCES remocra.rapport_personnalise(rapport_personnalise_id);

ALTER TABLE remocra.l_rapport_personnalise_groupe_fonctionnalites RENAME CONSTRAINT l_rapport_personnalise_profil_droit_pkey TO l_rapport_personnalise_profil_groupe_fonctionnalites_pkey;

--Modifier l'enum type_objet
ALTER TYPE historique.type_objet RENAME VALUE 'PROFIL_DROIT' TO 'GROUPE_FONCTIONNALITES';