ALTER TYPE remocra."DROIT" RENAME VALUE 'ADMIN_GROUPE_UTILISATEUR' TO 'GEST_CONTACT_A';
ALTER TYPE remocra."DROIT" ADD VALUE 'ORGANISME_CONTACT_A';
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_ORGANISME_A'; -- administrer organismes
ALTER TYPE remocra."DROIT" ADD VALUE 'ADMIN_ORGANISME_R'; -- consulter organismes
