/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl
import remocra.db.jooq.DefaultCatalog
import remocra.db.jooq.entrepotsig.tables.VCommuneSig
import remocra.db.jooq.entrepotsig.tables.VVoieSig
import javax.annotation.processing.Generated
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
open class Entrepotsig : SchemaImpl("entrepotsig", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>entrepotsig</code>
         */
        val ENTREPOTSIG: Entrepotsig = Entrepotsig()
    }

    /**
     * The table <code>entrepotsig.v_commune_sig</code>.
     */
    val V_COMMUNE_SIG: VCommuneSig get() = VCommuneSig.V_COMMUNE_SIG

    /**
     * The table <code>entrepotsig.v_voie_sig</code>.
     */
    val V_VOIE_SIG: VVoieSig get() = VVoieSig.V_VOIE_SIG

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        VCommuneSig.V_COMMUNE_SIG,
        VVoieSig.V_VOIE_SIG,
    )
}
