/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.incoming.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.bindings.ZonedDateTimeBinding
import remocra.db.jooq.incoming.Incoming
import remocra.db.jooq.incoming.keys.PHOTO_PEI_PKEY
import remocra.db.jooq.incoming.keys.PHOTO_PEI__PHOTO_PEI_PEI_ID_FKEY
import remocra.db.jooq.remocra.tables.Pei.PeiPath
import java.time.ZonedDateTime
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class PhotoPei(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Incoming.INCOMING,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>incoming.photo_pei</code>
         */
        val PHOTO_PEI: PhotoPei = PhotoPei()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>incoming.photo_pei.photo_id</code>.
     */
    val PHOTO_ID: TableField<Record, UUID?> = createField(DSL.name("photo_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>incoming.photo_pei.pei_id</code>.
     */
    val PEI_ID: TableField<Record, UUID?> = createField(DSL.name("pei_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>incoming.photo_pei.photo_libelle</code>.
     */
    val PHOTO_LIBELLE: TableField<Record, String?> = createField(DSL.name("photo_libelle"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>incoming.photo_pei.photo_date</code>.
     */
    val PHOTO_DATE: TableField<Record, ZonedDateTime?> = createField(DSL.name("photo_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "", ZonedDateTimeBinding())

    /**
     * The column <code>incoming.photo_pei.photo_path</code>.
     */
    val PHOTO_PATH: TableField<Record, String?> = createField(DSL.name("photo_path"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>incoming.photo_pei</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>incoming.photo_pei</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>incoming.photo_pei</code> table reference
     */
    constructor() : this(DSL.name("photo_pei"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PHOTO_PEI, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = [
            "https://www.jooq.org",
            "jOOQ version:3.20.10",
        ],
        comments = "This class is generated by jOOQ",
    )
    open class PhotoPeiPath : PhotoPei, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): PhotoPeiPath = PhotoPeiPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PhotoPeiPath = PhotoPeiPath(alias, this)
        override fun `as`(alias: Table<*>): PhotoPeiPath = PhotoPeiPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Incoming.INCOMING
    override fun getPrimaryKey(): UniqueKey<Record> = PHOTO_PEI_PKEY
    override fun getReferences(): List<ForeignKey<Record, *>> = listOf(PHOTO_PEI__PHOTO_PEI_PEI_ID_FKEY)

    /**
     * Get the implicit join path to the <code>remocra.pei</code> table.
     */
    fun pei(): PeiPath = pei
    val pei: PeiPath by lazy { PeiPath(this, PHOTO_PEI__PHOTO_PEI_PEI_ID_FKEY, null) }
    override fun `as`(alias: String): PhotoPei = PhotoPei(DSL.name(alias), this)
    override fun `as`(alias: Name): PhotoPei = PhotoPei(alias, this)
    override fun `as`(alias: Table<*>): PhotoPei = PhotoPei(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PhotoPei = PhotoPei(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PhotoPei = PhotoPei(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PhotoPei = PhotoPei(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PhotoPei = PhotoPei(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PhotoPei = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PhotoPei = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PhotoPei = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PhotoPei = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PhotoPei = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PhotoPei = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PhotoPei = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PhotoPei = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PhotoPei = where(DSL.notExists(select))
}
