/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.incoming.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import remocra.db.jooq.bindings.ZonedDateTimeBinding
import remocra.db.jooq.incoming.Incoming
import remocra.db.jooq.incoming.keys.TOURNEE_PKEY
import remocra.db.jooq.incoming.keys.VISITE__VISITE_VISITE_TOURNEE_ID_FKEY
import remocra.db.jooq.incoming.tables.Visite.VisitePath
import remocra.db.jooq.remocra.enums.StatutSynchronisation
import java.time.ZonedDateTime
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.9",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class Tournee(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Incoming.INCOMING,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>incoming.tournee</code>
         */
        val TOURNEE: Tournee = Tournee()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>incoming.tournee.tournee_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("tournee_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>incoming.tournee.tournee_libelle</code>.
     */
    val LIBELLE: TableField<Record, String?> = createField(DSL.name("tournee_libelle"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>incoming.tournee.tournee_date_debut_synchro</code>.
     */
    val DATE_DEBUT_SYNCHRO: TableField<Record, ZonedDateTime?> = createField(DSL.name("tournee_date_debut_synchro"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", ZonedDateTimeBinding())

    /**
     * The column <code>incoming.tournee.tournee_date_fin_synchro</code>.
     */
    val DATE_FIN_SYNCHRO: TableField<Record, ZonedDateTime?> = createField(DSL.name("tournee_date_fin_synchro"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", ZonedDateTimeBinding())

    /**
     * The column <code>incoming.tournee.tournee_statut_synchronisaiton</code>.
     */
    val STATUT_SYNCHRONISAITON: TableField<Record, StatutSynchronisation?> = createField(DSL.name("tournee_statut_synchronisaiton"), SQLDataType.VARCHAR.asEnumDataType(StatutSynchronisation::class.java), this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>incoming.tournee</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>incoming.tournee</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>incoming.tournee</code> table reference
     */
    constructor() : this(DSL.name("tournee"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TOURNEE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = [
            "https://www.jooq.org",
            "jOOQ version:3.20.9",
        ],
        comments = "This class is generated by jOOQ",
    )
    open class TourneePath : Tournee, Path<Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, Record>?, parentPath: InverseForeignKey<out Record, Record>?) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<Record>) : super(alias, aliased)
        override fun `as`(alias: String): TourneePath = TourneePath(DSL.name(alias), this)
        override fun `as`(alias: Name): TourneePath = TourneePath(alias, this)
        override fun `as`(alias: Table<*>): TourneePath = TourneePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Incoming.INCOMING
    override fun getPrimaryKey(): UniqueKey<Record> = TOURNEE_PKEY

    private lateinit var _visite: VisitePath

    /**
     * Get the implicit to-many join path to the <code>incoming.visite</code>
     * table
     */
    fun visite(): VisitePath {
        if (!this::_visite.isInitialized) {
            _visite = VisitePath(this, null, VISITE__VISITE_VISITE_TOURNEE_ID_FKEY.inverseKey)
        }

        return _visite
    }

    val visite: VisitePath
        get(): VisitePath = visite()
    override fun `as`(alias: String): Tournee = Tournee(DSL.name(alias), this)
    override fun `as`(alias: Name): Tournee = Tournee(alias, this)
    override fun `as`(alias: Table<*>): Tournee = Tournee(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tournee = Tournee(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tournee = Tournee(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Tournee = Tournee(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Tournee = Tournee(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Tournee = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Tournee = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Tournee = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Tournee = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Tournee = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Tournee = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Tournee = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Tournee = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Tournee = where(DSL.notExists(select))
}
