/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
data class Anomalie(
    val anomalieId: UUID,
    val anomalieCode: String,
    val anomalieLibelle: String,
    val anomalieCommentaire: String?,
    val anomalieAnomalieCategorieId: UUID,
    val anomalieActif: Boolean,
    val anomalieProtected: Boolean,
    val anomalieRendNonConforme: Boolean,
    val anomalieOrdre: Int?,
    val anomaliePoidsAnomalieSystemeValIndispoTerrestre: Int?,
    val anomaliePoidsAnomalieSystemeValIndispoHbe: Int?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: Anomalie = other as Anomalie
        if (this.anomalieId != o.anomalieId) {
            return false
        }
        if (this.anomalieCode != o.anomalieCode) {
            return false
        }
        if (this.anomalieLibelle != o.anomalieLibelle) {
            return false
        }
        if (this.anomalieCommentaire == null) {
            if (o.anomalieCommentaire != null) {
                return false
            }
        } else if (this.anomalieCommentaire != o.anomalieCommentaire) {
            return false
        }
        if (this.anomalieAnomalieCategorieId != o.anomalieAnomalieCategorieId) {
            return false
        }
        if (this.anomalieActif != o.anomalieActif) {
            return false
        }
        if (this.anomalieProtected != o.anomalieProtected) {
            return false
        }
        if (this.anomalieRendNonConforme != o.anomalieRendNonConforme) {
            return false
        }
        if (this.anomalieOrdre == null) {
            if (o.anomalieOrdre != null) {
                return false
            }
        } else if (this.anomalieOrdre != o.anomalieOrdre) {
            return false
        }
        if (this.anomaliePoidsAnomalieSystemeValIndispoTerrestre == null) {
            if (o.anomaliePoidsAnomalieSystemeValIndispoTerrestre != null) {
                return false
            }
        } else if (this.anomaliePoidsAnomalieSystemeValIndispoTerrestre != o.anomaliePoidsAnomalieSystemeValIndispoTerrestre) {
            return false
        }
        if (this.anomaliePoidsAnomalieSystemeValIndispoHbe == null) {
            if (o.anomaliePoidsAnomalieSystemeValIndispoHbe != null) {
                return false
            }
        } else if (this.anomaliePoidsAnomalieSystemeValIndispoHbe != o.anomaliePoidsAnomalieSystemeValIndispoHbe) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.anomalieId.hashCode()
        result = prime * result + this.anomalieCode.hashCode()
        result = prime * result + this.anomalieLibelle.hashCode()
        result = prime * result + (if (this.anomalieCommentaire == null) 0 else this.anomalieCommentaire.hashCode())
        result = prime * result + this.anomalieAnomalieCategorieId.hashCode()
        result = prime * result + this.anomalieActif.hashCode()
        result = prime * result + this.anomalieProtected.hashCode()
        result = prime * result + this.anomalieRendNonConforme.hashCode()
        result = prime * result + (if (this.anomalieOrdre == null) 0 else this.anomalieOrdre.hashCode())
        result = prime * result + (if (this.anomaliePoidsAnomalieSystemeValIndispoTerrestre == null) 0 else this.anomaliePoidsAnomalieSystemeValIndispoTerrestre.hashCode())
        result = prime * result + (if (this.anomaliePoidsAnomalieSystemeValIndispoHbe == null) 0 else this.anomaliePoidsAnomalieSystemeValIndispoHbe.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Anomalie (")

        sb.append(anomalieId)
        sb.append(", ").append(anomalieCode)
        sb.append(", ").append(anomalieLibelle)
        sb.append(", ").append(anomalieCommentaire)
        sb.append(", ").append(anomalieAnomalieCategorieId)
        sb.append(", ").append(anomalieActif)
        sb.append(", ").append(anomalieProtected)
        sb.append(", ").append(anomalieRendNonConforme)
        sb.append(", ").append(anomalieOrdre)
        sb.append(", ").append(anomaliePoidsAnomalieSystemeValIndispoTerrestre)
        sb.append(", ").append(anomaliePoidsAnomalieSystemeValIndispoHbe)

        sb.append(")")
        return sb.toString()
    }
}
