/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import org.locationtech.jts.geom.Geometry
import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class AtlasDocument(
    val atlasDocumentId: UUID,
    val atlasDocumentDocumentId: UUID?,
    val atlasDocumentActif: Boolean,
    val atlasDocumentGeometrie: Geometry,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: AtlasDocument = other as AtlasDocument
        if (this.atlasDocumentId != o.atlasDocumentId) {
            return false
        }
        if (this.atlasDocumentDocumentId == null) {
            if (o.atlasDocumentDocumentId != null) {
                return false
            }
        } else if (this.atlasDocumentDocumentId != o.atlasDocumentDocumentId) {
            return false
        }
        if (this.atlasDocumentActif != o.atlasDocumentActif) {
            return false
        }
        if (this.atlasDocumentGeometrie != o.atlasDocumentGeometrie) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.atlasDocumentId.hashCode()
        result = prime * result + (if (this.atlasDocumentDocumentId == null) 0 else this.atlasDocumentDocumentId.hashCode())
        result = prime * result + this.atlasDocumentActif.hashCode()
        result = prime * result + this.atlasDocumentGeometrie.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("AtlasDocument (")

        sb.append(atlasDocumentId)
        sb.append(", ").append(atlasDocumentDocumentId)
        sb.append(", ").append(atlasDocumentActif)
        sb.append(", ").append(atlasDocumentGeometrie)

        sb.append(")")
        return sb.toString()
    }
}
