/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import remocra.db.jooq.remocra.enums.TypeCivilite
import remocra.db.jooq.remocra.enums.TypeFonction
import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
data class Contact(
    val contactId: UUID,
    val contactActif: Boolean,
    val contactCivilite: TypeCivilite?,
    val contactFonction: TypeFonction?,
    val contactNom: String?,
    val contactPrenom: String?,
    val contactNumeroVoie: String?,
    val contactSuffixeVoie: String?,
    val contactLieuDit: String?,
    val contactVoie: String?,
    val contactCodePostal: String?,
    val contactVille: String?,
    val contactPays: String?,
    val contactTelephone: String?,
    val contactEmail: String?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: Contact = other as Contact
        if (this.contactId != o.contactId) {
            return false
        }
        if (this.contactActif != o.contactActif) {
            return false
        }
        if (this.contactCivilite == null) {
            if (o.contactCivilite != null) {
                return false
            }
        } else if (this.contactCivilite != o.contactCivilite) {
            return false
        }
        if (this.contactFonction == null) {
            if (o.contactFonction != null) {
                return false
            }
        } else if (this.contactFonction != o.contactFonction) {
            return false
        }
        if (this.contactNom == null) {
            if (o.contactNom != null) {
                return false
            }
        } else if (this.contactNom != o.contactNom) {
            return false
        }
        if (this.contactPrenom == null) {
            if (o.contactPrenom != null) {
                return false
            }
        } else if (this.contactPrenom != o.contactPrenom) {
            return false
        }
        if (this.contactNumeroVoie == null) {
            if (o.contactNumeroVoie != null) {
                return false
            }
        } else if (this.contactNumeroVoie != o.contactNumeroVoie) {
            return false
        }
        if (this.contactSuffixeVoie == null) {
            if (o.contactSuffixeVoie != null) {
                return false
            }
        } else if (this.contactSuffixeVoie != o.contactSuffixeVoie) {
            return false
        }
        if (this.contactLieuDit == null) {
            if (o.contactLieuDit != null) {
                return false
            }
        } else if (this.contactLieuDit != o.contactLieuDit) {
            return false
        }
        if (this.contactVoie == null) {
            if (o.contactVoie != null) {
                return false
            }
        } else if (this.contactVoie != o.contactVoie) {
            return false
        }
        if (this.contactCodePostal == null) {
            if (o.contactCodePostal != null) {
                return false
            }
        } else if (this.contactCodePostal != o.contactCodePostal) {
            return false
        }
        if (this.contactVille == null) {
            if (o.contactVille != null) {
                return false
            }
        } else if (this.contactVille != o.contactVille) {
            return false
        }
        if (this.contactPays == null) {
            if (o.contactPays != null) {
                return false
            }
        } else if (this.contactPays != o.contactPays) {
            return false
        }
        if (this.contactTelephone == null) {
            if (o.contactTelephone != null) {
                return false
            }
        } else if (this.contactTelephone != o.contactTelephone) {
            return false
        }
        if (this.contactEmail == null) {
            if (o.contactEmail != null) {
                return false
            }
        } else if (this.contactEmail != o.contactEmail) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.contactId.hashCode()
        result = prime * result + this.contactActif.hashCode()
        result = prime * result + (if (this.contactCivilite == null) 0 else this.contactCivilite.hashCode())
        result = prime * result + (if (this.contactFonction == null) 0 else this.contactFonction.hashCode())
        result = prime * result + (if (this.contactNom == null) 0 else this.contactNom.hashCode())
        result = prime * result + (if (this.contactPrenom == null) 0 else this.contactPrenom.hashCode())
        result = prime * result + (if (this.contactNumeroVoie == null) 0 else this.contactNumeroVoie.hashCode())
        result = prime * result + (if (this.contactSuffixeVoie == null) 0 else this.contactSuffixeVoie.hashCode())
        result = prime * result + (if (this.contactLieuDit == null) 0 else this.contactLieuDit.hashCode())
        result = prime * result + (if (this.contactVoie == null) 0 else this.contactVoie.hashCode())
        result = prime * result + (if (this.contactCodePostal == null) 0 else this.contactCodePostal.hashCode())
        result = prime * result + (if (this.contactVille == null) 0 else this.contactVille.hashCode())
        result = prime * result + (if (this.contactPays == null) 0 else this.contactPays.hashCode())
        result = prime * result + (if (this.contactTelephone == null) 0 else this.contactTelephone.hashCode())
        result = prime * result + (if (this.contactEmail == null) 0 else this.contactEmail.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Contact (")

        sb.append(contactId)
        sb.append(", ").append(contactActif)
        sb.append(", ").append(contactCivilite)
        sb.append(", ").append(contactFonction)
        sb.append(", ").append(contactNom)
        sb.append(", ").append(contactPrenom)
        sb.append(", ").append(contactNumeroVoie)
        sb.append(", ").append(contactSuffixeVoie)
        sb.append(", ").append(contactLieuDit)
        sb.append(", ").append(contactVoie)
        sb.append(", ").append(contactCodePostal)
        sb.append(", ").append(contactVille)
        sb.append(", ").append(contactPays)
        sb.append(", ").append(contactTelephone)
        sb.append(", ").append(contactEmail)

        sb.append(")")
        return sb.toString()
    }
}
