/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
data class CriseCategorie(
    val criseCategorieId: UUID,
    val criseCategorieCode: String,
    val criseCategorieLibelle: String,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: CriseCategorie = other as CriseCategorie
        if (this.criseCategorieId != o.criseCategorieId) {
            return false
        }
        if (this.criseCategorieCode != o.criseCategorieCode) {
            return false
        }
        if (this.criseCategorieLibelle != o.criseCategorieLibelle) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.criseCategorieId.hashCode()
        result = prime * result + this.criseCategorieCode.hashCode()
        result = prime * result + this.criseCategorieLibelle.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CriseCategorie (")

        sb.append(criseCategorieId)
        sb.append(", ").append(criseCategorieCode)
        sb.append(", ").append(criseCategorieLibelle)

        sb.append(")")
        return sb.toString()
    }
}
