/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import org.jooq.JSONB
import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class DashboardConfig(
    val dashboardConfigDashboardComponentId: UUID,
    val dashboardConfigDashboardId: UUID,
    val dashboardConfigDashboardComponentPositionConfig: JSONB,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: DashboardConfig = other as DashboardConfig
        if (this.dashboardConfigDashboardComponentId != o.dashboardConfigDashboardComponentId) {
            return false
        }
        if (this.dashboardConfigDashboardId != o.dashboardConfigDashboardId) {
            return false
        }
        if (this.dashboardConfigDashboardComponentPositionConfig != o.dashboardConfigDashboardComponentPositionConfig) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.dashboardConfigDashboardComponentId.hashCode()
        result = prime * result + this.dashboardConfigDashboardId.hashCode()
        result = prime * result + this.dashboardConfigDashboardComponentPositionConfig.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("DashboardConfig (")

        sb.append(dashboardConfigDashboardComponentId)
        sb.append(", ").append(dashboardConfigDashboardId)
        sb.append(", ").append(dashboardConfigDashboardComponentPositionConfig)

        sb.append(")")
        return sb.toString()
    }
}
