/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.time.ZonedDateTime
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class DocumentHabilitable(
    val documentHabilitableId: UUID,
    val documentId: UUID,
    val documentHabilitableLibelle: String?,
    val documentHabilitableDescription: String?,
    val documentHabilitableDateMaj: ZonedDateTime?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: DocumentHabilitable = other as DocumentHabilitable
        if (this.documentHabilitableId != o.documentHabilitableId) {
            return false
        }
        if (this.documentId != o.documentId) {
            return false
        }
        if (this.documentHabilitableLibelle == null) {
            if (o.documentHabilitableLibelle != null) {
                return false
            }
        } else if (this.documentHabilitableLibelle != o.documentHabilitableLibelle) {
            return false
        }
        if (this.documentHabilitableDescription == null) {
            if (o.documentHabilitableDescription != null) {
                return false
            }
        } else if (this.documentHabilitableDescription != o.documentHabilitableDescription) {
            return false
        }
        if (this.documentHabilitableDateMaj == null) {
            if (o.documentHabilitableDateMaj != null) {
                return false
            }
        } else if (this.documentHabilitableDateMaj != o.documentHabilitableDateMaj) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.documentHabilitableId.hashCode()
        result = prime * result + this.documentId.hashCode()
        result = prime * result + (if (this.documentHabilitableLibelle == null) 0 else this.documentHabilitableLibelle.hashCode())
        result = prime * result + (if (this.documentHabilitableDescription == null) 0 else this.documentHabilitableDescription.hashCode())
        result = prime * result + (if (this.documentHabilitableDateMaj == null) 0 else this.documentHabilitableDateMaj.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("DocumentHabilitable (")

        sb.append(documentHabilitableId)
        sb.append(", ").append(documentId)
        sb.append(", ").append(documentHabilitableLibelle)
        sb.append(", ").append(documentHabilitableDescription)
        sb.append(", ").append(documentHabilitableDateMaj)

        sb.append(")")
        return sb.toString()
    }
}
