/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.9",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class LContactRole(
    val contactId: UUID,
    val roleId: UUID,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: LContactRole = other as LContactRole
        if (this.contactId != o.contactId) {
            return false
        }
        if (this.roleId != o.roleId) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.contactId.hashCode()
        result = prime * result + this.roleId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("LContactRole (")

        sb.append(contactId)
        sb.append(", ").append(roleId)

        sb.append(")")
        return sb.toString()
    }
}
