/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class LDashboardProfil(
    val profilUtilisateurId: UUID,
    val dashboardId: UUID,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: LDashboardProfil = other as LDashboardProfil
        if (this.profilUtilisateurId != o.profilUtilisateurId) {
            return false
        }
        if (this.dashboardId != o.dashboardId) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.profilUtilisateurId.hashCode()
        result = prime * result + this.dashboardId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("LDashboardProfil (")

        sb.append(profilUtilisateurId)
        sb.append(", ").append(dashboardId)

        sb.append(")")
        return sb.toString()
    }
}
