/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class LEvenementDocument(
    val evenementId: UUID,
    val documentId: UUID,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: LEvenementDocument = other as LEvenementDocument
        if (this.evenementId != o.evenementId) {
            return false
        }
        if (this.documentId != o.documentId) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.evenementId.hashCode()
        result = prime * result + this.documentId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("LEvenementDocument (")

        sb.append(evenementId)
        sb.append(", ").append(documentId)

        sb.append(")")
        return sb.toString()
    }
}
