/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
data class LGroupeFonctionnalitesDocumentHabilitable(
    val groupeFonctionnalitesId: UUID,
    val documentHabilitableId: UUID,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: LGroupeFonctionnalitesDocumentHabilitable = other as LGroupeFonctionnalitesDocumentHabilitable
        if (this.groupeFonctionnalitesId != o.groupeFonctionnalitesId) {
            return false
        }
        if (this.documentHabilitableId != o.documentHabilitableId) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.groupeFonctionnalitesId.hashCode()
        result = prime * result + this.documentHabilitableId.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("LGroupeFonctionnalitesDocumentHabilitable (")

        sb.append(groupeFonctionnalitesId)
        sb.append(", ").append(documentHabilitableId)

        sb.append(")")
        return sb.toString()
    }
}
