/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import remocra.db.jooq.remocra.enums.TypeParametreCourrier
import java.io.Serializable
import java.math.BigDecimal
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.3",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
data class ModeleCourrierParametre(
    val modeleCourrierParametreModeleCourrierId: UUID,
    val modeleCourrierParametreTypeParametreCourrier: TypeParametreCourrier,
    val modeleCourrierParametreLibelle: String,
    val modeleCourrierParametreDescription: String?,
    val modeleCourrierParametreOrdre: BigDecimal?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: ModeleCourrierParametre = other as ModeleCourrierParametre
        if (this.modeleCourrierParametreModeleCourrierId != o.modeleCourrierParametreModeleCourrierId) {
            return false
        }
        if (this.modeleCourrierParametreTypeParametreCourrier != o.modeleCourrierParametreTypeParametreCourrier) {
            return false
        }
        if (this.modeleCourrierParametreLibelle != o.modeleCourrierParametreLibelle) {
            return false
        }
        if (this.modeleCourrierParametreDescription == null) {
            if (o.modeleCourrierParametreDescription != null) {
                return false
            }
        } else if (this.modeleCourrierParametreDescription != o.modeleCourrierParametreDescription) {
            return false
        }
        if (this.modeleCourrierParametreOrdre == null) {
            if (o.modeleCourrierParametreOrdre != null) {
                return false
            }
        } else if (this.modeleCourrierParametreOrdre != o.modeleCourrierParametreOrdre) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.modeleCourrierParametreModeleCourrierId.hashCode()
        result = prime * result + this.modeleCourrierParametreTypeParametreCourrier.hashCode()
        result = prime * result + this.modeleCourrierParametreLibelle.hashCode()
        result = prime * result + (if (this.modeleCourrierParametreDescription == null) 0 else this.modeleCourrierParametreDescription.hashCode())
        result = prime * result + (if (this.modeleCourrierParametreOrdre == null) 0 else this.modeleCourrierParametreOrdre.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ModeleCourrierParametre (")

        sb.append(modeleCourrierParametreModeleCourrierId)
        sb.append(", ").append(modeleCourrierParametreTypeParametreCourrier)
        sb.append(", ").append(modeleCourrierParametreLibelle)
        sb.append(", ").append(modeleCourrierParametreDescription)
        sb.append(", ").append(modeleCourrierParametreOrdre)

        sb.append(")")
        return sb.toString()
    }
}
