/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.3",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
data class NatureDeci(
    val natureDeciId: UUID,
    val natureDeciCode: String,
    val natureDeciNom: String,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: NatureDeci = other as NatureDeci
        if (this.natureDeciId != o.natureDeciId) {
            return false
        }
        if (this.natureDeciCode != o.natureDeciCode) {
            return false
        }
        if (this.natureDeciNom != o.natureDeciNom) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.natureDeciId.hashCode()
        result = prime * result + this.natureDeciCode.hashCode()
        result = prime * result + this.natureDeciNom.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("NatureDeci (")

        sb.append(natureDeciId)
        sb.append(", ").append(natureDeciCode)
        sb.append(", ").append(natureDeciNom)

        sb.append(")")
        return sb.toString()
    }
}
