/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class OldebTypeSuite(
    val oldebTypeSuiteId: UUID,
    val oldebTypeSuiteActif: Boolean,
    val oldebTypeSuiteCode: String,
    val oldebTypeSuiteLibelle: String,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: OldebTypeSuite = other as OldebTypeSuite
        if (this.oldebTypeSuiteId != o.oldebTypeSuiteId) {
            return false
        }
        if (this.oldebTypeSuiteActif != o.oldebTypeSuiteActif) {
            return false
        }
        if (this.oldebTypeSuiteCode != o.oldebTypeSuiteCode) {
            return false
        }
        if (this.oldebTypeSuiteLibelle != o.oldebTypeSuiteLibelle) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.oldebTypeSuiteId.hashCode()
        result = prime * result + this.oldebTypeSuiteActif.hashCode()
        result = prime * result + this.oldebTypeSuiteCode.hashCode()
        result = prime * result + this.oldebTypeSuiteLibelle.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("OldebTypeSuite (")

        sb.append(oldebTypeSuiteId)
        sb.append(", ").append(oldebTypeSuiteActif)
        sb.append(", ").append(oldebTypeSuiteCode)
        sb.append(", ").append(oldebTypeSuiteLibelle)

        sb.append(")")
        return sb.toString()
    }
}
