/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.9",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class OldebTypeAcces(
    val oldebTypeAccesId: UUID,
    val oldebTypeAccesActif: Boolean,
    val oldebTypeAccesCode: String,
    val oldebTypeAccesLibelle: String,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: OldebTypeAcces = other as OldebTypeAcces
        if (this.oldebTypeAccesId != o.oldebTypeAccesId) {
            return false
        }
        if (this.oldebTypeAccesActif != o.oldebTypeAccesActif) {
            return false
        }
        if (this.oldebTypeAccesCode != o.oldebTypeAccesCode) {
            return false
        }
        if (this.oldebTypeAccesLibelle != o.oldebTypeAccesLibelle) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.oldebTypeAccesId.hashCode()
        result = prime * result + this.oldebTypeAccesActif.hashCode()
        result = prime * result + this.oldebTypeAccesCode.hashCode()
        result = prime * result + this.oldebTypeAccesLibelle.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("OldebTypeAcces (")

        sb.append(oldebTypeAccesId)
        sb.append(", ").append(oldebTypeAccesActif)
        sb.append(", ").append(oldebTypeAccesCode)
        sb.append(", ").append(oldebTypeAccesLibelle)

        sb.append(")")
        return sb.toString()
    }
}
