/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.tables.pojos

import org.locationtech.jts.geom.Geometry
import remocra.db.jooq.remocra.enums.Direction
import remocra.db.jooq.remocra.enums.OuiNonNa
import remocra.db.jooq.remocra.enums.RisqueMeteo
import java.io.Serializable
import java.time.ZonedDateTime
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.19.11",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("UNCHECKED_CAST")
data class Rcci(
    val rcciId: UUID,
    val rcciCommentaireConclusion: String?,
    val rcciComplement: String?,
    val rcciCarroyageDfci: String?,
    val rcciDateIncendie: ZonedDateTime,
    val rcciDateModification: ZonedDateTime,
    val rcciDirectionVent: Direction?,
    val rcciForceVent: Int?,
    val rcciForcesOrdre: String?,
    val rcciGdh: ZonedDateTime?,
    val rcciGeometrie: Geometry,
    val rcciHygrometrie: Int?,
    val rcciPointEclosion: String?,
    val rcciPremierCos: String?,
    val rcciPremierEngin: String?,
    val rcciSuperficieFinale: Double?,
    val rcciSuperficieReferent: Double?,
    val rcciSuperficieSecours: Double?,
    val rcciTemperature: Double?,
    val rcciVoieTexte: String?,
    val rcciCommuneId: UUID?,
    val rcciRcciTypePrometheeCategorieId: UUID?,
    val rcciRcciTypeDegreCertitudeId: UUID?,
    val rcciRcciTypeOrigineAlerteId: UUID,
    val rcciRcciArriveeDdtmOnfId: UUID?,
    val rcciRcciArriveeSdisId: UUID?,
    val rcciRcciArriveeGendarmerieId: UUID?,
    val rcciRcciArriveePoliceId: UUID?,
    val rcciUtilisateurId: UUID,
    val rcciRisqueMeteo: RisqueMeteo?,
    val rcciRcciIndiceRothermelId: UUID?,
    val rcciVentLocal: OuiNonNa?,
    val rcciGelLieux: OuiNonNa?,
    val rcciVoieId: UUID?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: Rcci = other as Rcci
        if (this.rcciId != o.rcciId) {
            return false
        }
        if (this.rcciCommentaireConclusion == null) {
            if (o.rcciCommentaireConclusion != null) {
                return false
            }
        } else if (this.rcciCommentaireConclusion != o.rcciCommentaireConclusion) {
            return false
        }
        if (this.rcciComplement == null) {
            if (o.rcciComplement != null) {
                return false
            }
        } else if (this.rcciComplement != o.rcciComplement) {
            return false
        }
        if (this.rcciCarroyageDfci == null) {
            if (o.rcciCarroyageDfci != null) {
                return false
            }
        } else if (this.rcciCarroyageDfci != o.rcciCarroyageDfci) {
            return false
        }
        if (this.rcciDateIncendie != o.rcciDateIncendie) {
            return false
        }
        if (this.rcciDateModification != o.rcciDateModification) {
            return false
        }
        if (this.rcciDirectionVent == null) {
            if (o.rcciDirectionVent != null) {
                return false
            }
        } else if (this.rcciDirectionVent != o.rcciDirectionVent) {
            return false
        }
        if (this.rcciForceVent == null) {
            if (o.rcciForceVent != null) {
                return false
            }
        } else if (this.rcciForceVent != o.rcciForceVent) {
            return false
        }
        if (this.rcciForcesOrdre == null) {
            if (o.rcciForcesOrdre != null) {
                return false
            }
        } else if (this.rcciForcesOrdre != o.rcciForcesOrdre) {
            return false
        }
        if (this.rcciGdh == null) {
            if (o.rcciGdh != null) {
                return false
            }
        } else if (this.rcciGdh != o.rcciGdh) {
            return false
        }
        if (this.rcciGeometrie != o.rcciGeometrie) {
            return false
        }
        if (this.rcciHygrometrie == null) {
            if (o.rcciHygrometrie != null) {
                return false
            }
        } else if (this.rcciHygrometrie != o.rcciHygrometrie) {
            return false
        }
        if (this.rcciPointEclosion == null) {
            if (o.rcciPointEclosion != null) {
                return false
            }
        } else if (this.rcciPointEclosion != o.rcciPointEclosion) {
            return false
        }
        if (this.rcciPremierCos == null) {
            if (o.rcciPremierCos != null) {
                return false
            }
        } else if (this.rcciPremierCos != o.rcciPremierCos) {
            return false
        }
        if (this.rcciPremierEngin == null) {
            if (o.rcciPremierEngin != null) {
                return false
            }
        } else if (this.rcciPremierEngin != o.rcciPremierEngin) {
            return false
        }
        if (this.rcciSuperficieFinale == null) {
            if (o.rcciSuperficieFinale != null) {
                return false
            }
        } else if (this.rcciSuperficieFinale != o.rcciSuperficieFinale) {
            return false
        }
        if (this.rcciSuperficieReferent == null) {
            if (o.rcciSuperficieReferent != null) {
                return false
            }
        } else if (this.rcciSuperficieReferent != o.rcciSuperficieReferent) {
            return false
        }
        if (this.rcciSuperficieSecours == null) {
            if (o.rcciSuperficieSecours != null) {
                return false
            }
        } else if (this.rcciSuperficieSecours != o.rcciSuperficieSecours) {
            return false
        }
        if (this.rcciTemperature == null) {
            if (o.rcciTemperature != null) {
                return false
            }
        } else if (this.rcciTemperature != o.rcciTemperature) {
            return false
        }
        if (this.rcciVoieTexte == null) {
            if (o.rcciVoieTexte != null) {
                return false
            }
        } else if (this.rcciVoieTexte != o.rcciVoieTexte) {
            return false
        }
        if (this.rcciCommuneId == null) {
            if (o.rcciCommuneId != null) {
                return false
            }
        } else if (this.rcciCommuneId != o.rcciCommuneId) {
            return false
        }
        if (this.rcciRcciTypePrometheeCategorieId == null) {
            if (o.rcciRcciTypePrometheeCategorieId != null) {
                return false
            }
        } else if (this.rcciRcciTypePrometheeCategorieId != o.rcciRcciTypePrometheeCategorieId) {
            return false
        }
        if (this.rcciRcciTypeDegreCertitudeId == null) {
            if (o.rcciRcciTypeDegreCertitudeId != null) {
                return false
            }
        } else if (this.rcciRcciTypeDegreCertitudeId != o.rcciRcciTypeDegreCertitudeId) {
            return false
        }
        if (this.rcciRcciTypeOrigineAlerteId != o.rcciRcciTypeOrigineAlerteId) {
            return false
        }
        if (this.rcciRcciArriveeDdtmOnfId == null) {
            if (o.rcciRcciArriveeDdtmOnfId != null) {
                return false
            }
        } else if (this.rcciRcciArriveeDdtmOnfId != o.rcciRcciArriveeDdtmOnfId) {
            return false
        }
        if (this.rcciRcciArriveeSdisId == null) {
            if (o.rcciRcciArriveeSdisId != null) {
                return false
            }
        } else if (this.rcciRcciArriveeSdisId != o.rcciRcciArriveeSdisId) {
            return false
        }
        if (this.rcciRcciArriveeGendarmerieId == null) {
            if (o.rcciRcciArriveeGendarmerieId != null) {
                return false
            }
        } else if (this.rcciRcciArriveeGendarmerieId != o.rcciRcciArriveeGendarmerieId) {
            return false
        }
        if (this.rcciRcciArriveePoliceId == null) {
            if (o.rcciRcciArriveePoliceId != null) {
                return false
            }
        } else if (this.rcciRcciArriveePoliceId != o.rcciRcciArriveePoliceId) {
            return false
        }
        if (this.rcciUtilisateurId != o.rcciUtilisateurId) {
            return false
        }
        if (this.rcciRisqueMeteo == null) {
            if (o.rcciRisqueMeteo != null) {
                return false
            }
        } else if (this.rcciRisqueMeteo != o.rcciRisqueMeteo) {
            return false
        }
        if (this.rcciRcciIndiceRothermelId == null) {
            if (o.rcciRcciIndiceRothermelId != null) {
                return false
            }
        } else if (this.rcciRcciIndiceRothermelId != o.rcciRcciIndiceRothermelId) {
            return false
        }
        if (this.rcciVentLocal == null) {
            if (o.rcciVentLocal != null) {
                return false
            }
        } else if (this.rcciVentLocal != o.rcciVentLocal) {
            return false
        }
        if (this.rcciGelLieux == null) {
            if (o.rcciGelLieux != null) {
                return false
            }
        } else if (this.rcciGelLieux != o.rcciGelLieux) {
            return false
        }
        if (this.rcciVoieId == null) {
            if (o.rcciVoieId != null) {
                return false
            }
        } else if (this.rcciVoieId != o.rcciVoieId) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.rcciId.hashCode()
        result = prime * result + (if (this.rcciCommentaireConclusion == null) 0 else this.rcciCommentaireConclusion.hashCode())
        result = prime * result + (if (this.rcciComplement == null) 0 else this.rcciComplement.hashCode())
        result = prime * result + (if (this.rcciCarroyageDfci == null) 0 else this.rcciCarroyageDfci.hashCode())
        result = prime * result + this.rcciDateIncendie.hashCode()
        result = prime * result + this.rcciDateModification.hashCode()
        result = prime * result + (if (this.rcciDirectionVent == null) 0 else this.rcciDirectionVent.hashCode())
        result = prime * result + (if (this.rcciForceVent == null) 0 else this.rcciForceVent.hashCode())
        result = prime * result + (if (this.rcciForcesOrdre == null) 0 else this.rcciForcesOrdre.hashCode())
        result = prime * result + (if (this.rcciGdh == null) 0 else this.rcciGdh.hashCode())
        result = prime * result + this.rcciGeometrie.hashCode()
        result = prime * result + (if (this.rcciHygrometrie == null) 0 else this.rcciHygrometrie.hashCode())
        result = prime * result + (if (this.rcciPointEclosion == null) 0 else this.rcciPointEclosion.hashCode())
        result = prime * result + (if (this.rcciPremierCos == null) 0 else this.rcciPremierCos.hashCode())
        result = prime * result + (if (this.rcciPremierEngin == null) 0 else this.rcciPremierEngin.hashCode())
        result = prime * result + (if (this.rcciSuperficieFinale == null) 0 else this.rcciSuperficieFinale.hashCode())
        result = prime * result + (if (this.rcciSuperficieReferent == null) 0 else this.rcciSuperficieReferent.hashCode())
        result = prime * result + (if (this.rcciSuperficieSecours == null) 0 else this.rcciSuperficieSecours.hashCode())
        result = prime * result + (if (this.rcciTemperature == null) 0 else this.rcciTemperature.hashCode())
        result = prime * result + (if (this.rcciVoieTexte == null) 0 else this.rcciVoieTexte.hashCode())
        result = prime * result + (if (this.rcciCommuneId == null) 0 else this.rcciCommuneId.hashCode())
        result = prime * result + (if (this.rcciRcciTypePrometheeCategorieId == null) 0 else this.rcciRcciTypePrometheeCategorieId.hashCode())
        result = prime * result + (if (this.rcciRcciTypeDegreCertitudeId == null) 0 else this.rcciRcciTypeDegreCertitudeId.hashCode())
        result = prime * result + this.rcciRcciTypeOrigineAlerteId.hashCode()
        result = prime * result + (if (this.rcciRcciArriveeDdtmOnfId == null) 0 else this.rcciRcciArriveeDdtmOnfId.hashCode())
        result = prime * result + (if (this.rcciRcciArriveeSdisId == null) 0 else this.rcciRcciArriveeSdisId.hashCode())
        result = prime * result + (if (this.rcciRcciArriveeGendarmerieId == null) 0 else this.rcciRcciArriveeGendarmerieId.hashCode())
        result = prime * result + (if (this.rcciRcciArriveePoliceId == null) 0 else this.rcciRcciArriveePoliceId.hashCode())
        result = prime * result + this.rcciUtilisateurId.hashCode()
        result = prime * result + (if (this.rcciRisqueMeteo == null) 0 else this.rcciRisqueMeteo.hashCode())
        result = prime * result + (if (this.rcciRcciIndiceRothermelId == null) 0 else this.rcciRcciIndiceRothermelId.hashCode())
        result = prime * result + (if (this.rcciVentLocal == null) 0 else this.rcciVentLocal.hashCode())
        result = prime * result + (if (this.rcciGelLieux == null) 0 else this.rcciGelLieux.hashCode())
        result = prime * result + (if (this.rcciVoieId == null) 0 else this.rcciVoieId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Rcci (")

        sb.append(rcciId)
        sb.append(", ").append(rcciCommentaireConclusion)
        sb.append(", ").append(rcciComplement)
        sb.append(", ").append(rcciCarroyageDfci)
        sb.append(", ").append(rcciDateIncendie)
        sb.append(", ").append(rcciDateModification)
        sb.append(", ").append(rcciDirectionVent)
        sb.append(", ").append(rcciForceVent)
        sb.append(", ").append(rcciForcesOrdre)
        sb.append(", ").append(rcciGdh)
        sb.append(", ").append(rcciGeometrie)
        sb.append(", ").append(rcciHygrometrie)
        sb.append(", ").append(rcciPointEclosion)
        sb.append(", ").append(rcciPremierCos)
        sb.append(", ").append(rcciPremierEngin)
        sb.append(", ").append(rcciSuperficieFinale)
        sb.append(", ").append(rcciSuperficieReferent)
        sb.append(", ").append(rcciSuperficieSecours)
        sb.append(", ").append(rcciTemperature)
        sb.append(", ").append(rcciVoieTexte)
        sb.append(", ").append(rcciCommuneId)
        sb.append(", ").append(rcciRcciTypePrometheeCategorieId)
        sb.append(", ").append(rcciRcciTypeDegreCertitudeId)
        sb.append(", ").append(rcciRcciTypeOrigineAlerteId)
        sb.append(", ").append(rcciRcciArriveeDdtmOnfId)
        sb.append(", ").append(rcciRcciArriveeSdisId)
        sb.append(", ").append(rcciRcciArriveeGendarmerieId)
        sb.append(", ").append(rcciRcciArriveePoliceId)
        sb.append(", ").append(rcciUtilisateurId)
        sb.append(", ").append(rcciRisqueMeteo)
        sb.append(", ").append(rcciRcciIndiceRothermelId)
        sb.append(", ").append(rcciVentLocal)
        sb.append(", ").append(rcciGelLieux)
        sb.append(", ").append(rcciVoieId)

        sb.append(")")
        return sb.toString()
    }
}
