= REMOcRA - Document d’installation (DIT)
:Author:    Atol C&D
:Email:     remocra-projet@atolcd.com
:Date:      15/09/2025
:Revision:  1.0.0
:imagesdir: images/
:experimental:
:icons: font
:toc:
:numbered:

<<<
== Introduction générale

Ce document d’installation (DIT) est à destination des administrateurs système en charge de l’installation de l’outil REMOcRA. De ce fait, un niveau minimum de connaissances sur les technologies est requis, faute de quoi les informations contenues dans ce document ne pourront pas suffire.

== Présentation générale de l'outil REMOcRA

L’outil REMOcRA est détaillé dans le document d’architecture technique (DAT). Veuillez vous reporter à ce document pour obtenir plus d’informations sur le fonctionnement général de l'outil REMOcRA.

== Serveur d’application

WARNING: L'utilisation d'Apache HOP est par défaut désactivé dans l'application. Il n'est donc pas nécessaire de le mettre en place pour le bon fonctionnement de l'application et est totalement *facultatif*.

=== Prérequis

Pour l’installation de l’application, il a été choisi d’utiliser docker et compose pour tous les services. Il faut donc au préalable vous assurer que docker est bien présent et installer le plugins docker compose si nécessaire (voir https://docs.docker.com/engine/install/).
Il est également nécessaire de disposer d’une base de données PostgreSQL (version 16) nommée `remocra`, avec un utilisateur `remocra` et le mot de passe associé (à renseigner dans le fichier `.env`). Cette base devra avoir l’extension POSTGIS installée (version 3.6). Une seconde base PostgreSQL (version 16) doit être créée pour Keycloak, nommée `keycloak`, avec un utilisateur `keycloak` et son mot de passe (également à renseigner dans le fichier `.env`). Cette base devra contenir un schéma `keycloak`.

=== Dépôt du fichier compose.yaml

Créer un dossier `/opt/remocra`.

Dans ce dossier, ajouter un fichier nommé `compose.yaml`. Renseigner le contenu suivant :

[source,yaml]
----
include::compose-example.yaml[]
----

=== Mise en place des variables d’environnement
Pour que le fichier compose.yaml ait tous les paramètres, il faut créer dans le même répertoire `/opt/remocra/` un fichier `.env` qui contiendra les éléments suivants :

[source,properties]
----
DOCKER_REMOCRA_VERSION=1.0-a9

GLOWROOT_ENABLED=false
GLOWROOT_PORT=4000

OTEL_JAVAAGENT_ENABLED=false
OTEL_SERVICE_INSTANCE_ID=1

# Postgres
POSTGRES_DB_HOSTNAME=localhost
POSTGRES_DB_NAME=remocra
POSTGRES_DB_USERNAME=remocra
POSTGRES_DB_PASSWORD=xxxxxxxxxxxxxxxxxx

KC_BOOTSTRAP_ADMIN_USERNAME=kcadmin
KC_BOOTSTRAP_ADMIN_PASSWORD=xxxxxxxxxxxxxx
DB_PASSWORD_KEYCLOAK=xxxxxxxxxxxxxxx

# URL public de Keycloak
BASE_URI=https://xxxxxxxxxxxxxx-auth.com
DB_USER_KEYCLOAK=keycloak
CLIENT_ID=remocra
CLIENT_SECRET=remocra
REALM=remocra

# URL de l’application remocra
REMOCRA_URL=https://xxxxxxxxxxxxxxxxxxx

# Code de votre SDIS (par exemple SDIS_01)
CODE_SDIS=XXX
SMTP_USER=""
SMTP_PASSWORD=""
SMTP_FROM=""
SMTP_URL=""
SMTP_PORT=25
URL_SITE=""

EPSG_NAME="EPSG:2154"
EPSG_PROJECTION="+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

# APACHE HOP
APACHE_HOP_ENABLE=true
APACHE_HOP_URL=http://localhost:8060/hop
APACHE_HOP_USERNAME=admin
APACHE_HOP_PASSWORD=xxxxxxxxxxxxxxxxx

# Geoserver
GEOSERVER_URL=http://localhost:8090/geoserver
GEOSERVER_USER=admin
GEOSERVER_PASSWORD=xxxxxxxxxxxxxxxxx
----

=== Explication des variables d’environnement

|===
| | Description | Variable | Valeur par défaut

.4+| *Base de données*
| POSTGRES_DB_HOSTNAME | Nom d’hôte de la base de données PostgreSQL |
| POSTGRES_DB_NAME | Nom de la base de données PostgreSQL (par défaut _remocra_) | remocra
| POSTGRES_DB_USERNAME | Nom de l’utilisateur PostgreSQL (par défaut _remocra_)  | remocra
| POSTGRES_DB_PASSWORD | Mot de passe de l’utilisateur PostgreSQL  |
.5+| *Informations pour l’application REMOcRA*
| REMOCRA_URL | L’adresse https permettant à accéder à l’interface REMOcRA sans “/” à la fin.  |
| CODE_SDIS | Code du SDIS, doit correspondre à une valeur de l’énumération présente dans le fichier : https://github.com/SDIS83-GSIC/REMOcRA-Application/blob/master/app/src/main/kotlin/remocra/data/enums/CodeSdis.kt[] |
| EPSG_NAME | Nom de la projection (par exemple _EPSG:2154_) |
| EPSG_PROJECTION | La projection |
| REMOCRA_ENVIRONMENT a| Permet d'afficher l'information de l'environnement dans le header de l'application. Peut avoir les valeurs suivantes :

* DEVELOPPEMENT
* FORMATION
* RECETTE
* PREPRODUCTION
* PRODUCTION  | PRODUCTION

.5+| *Informations de connexion à la base SIG du SDIS
(les valeurs sont optionnelles)*
| SIG_HOSTNAME | |
| SIG_SQL_DIALECT | |
| SIG_DBNAME | |
| SIG_USERNAME | |
| SIG_PASSWORD | |

.6+| *Keycloak*
| KC_BOOTSTRAP_ADMIN_USERNAME | Nom de l’utilisateur super-admin pour se connecter à Keycloak |
| KC_BOOTSTRAP_ADMIN_PASSWORD | Mot de passe de l’utilisateur super-admin pour se connecter à Keycloak |
| CLIENT_SECRET | |
| CLIENT_ID | | remocra
| REALM | Valeur pour le realm utilisé dans keycloak. | remocra
| BASE_URI | L’adresse https permettant à accéder à l’interface keycloak |

.4+| *Apache Hop*
| APACHE_HOP_ENABLE | Activation d'Apache Hop dans l'application | `false`
| APACHE_HOP_URL | URL d'Apache Hop (facultatif si APACHE_HOP_ENABLE est à `false`) |
| APACHE_HOP_USERNAME | Login pour la connexion à Apache HOP (facultatif si APACHE_HOP_ENABLE est à `false`) |
| APACHE_HOP_PASSWORD | Mot de passe pour la connexion à Apache HOP (facultatif si APACHE_HOP_ENABLE est à `false`) |

.4+| *Glowroot*
| GLOWROOT_ENABLED | Activation de glowroot pour REMOcRA |
| GLOWROOT_PORT | Port de glowroot pour REMOcRA | 4000
| GEOSERVER_GLOWROOT_ENABLED | Activation de glowroot pour geoserver |
| GEOSERVER_GLOWROOT_PORT | Port de glowroot pour geoserver | 4001

.5+| *OpenTelemetry*
| OTEL_JAVAAGENT_ENABLED | Activation d'OpenTelemetry pour REMOcRA |
| OTEL_SERVICE_INSTANCE_ID | Identifiant de l'instance de REMOcRA (utile uniquement si vous avez plusieurs instances de REMOcRA sur le même serveur) | 1
2+| D'autres variables d'environnement peuvent être passées, https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/[plus d'informations sur la documentation en ligne] |
| GEOSERVER_OTEL_JAVAAGENT_ENABLED | Activation d'OpenTelemetry pour geoserver |
| GEOSERVER_OTEL_SERVICE_INSTANCE_ID | Identifiant de l'instance de REMOcRA (utile uniquement si vous avez plusieurs instances de GeoServer sur le même serveur) | 1

.5+| *Nexsis*
| NEXSIS_ENABLED | Activation de nexsis | false
| CODE_STRUCTURE | Code fourni par NexSIS pour la structure, à recopier exactement comme fourni. Exemple : "083-sis" pour le SDIS 83 |
| NEXSIS_URL | Url de nexsis | http://nexsis.gouv.fr
| NEXSIS_USER | Utilisateur de connexion à nexsis |
| NEXSIS_PASSWORD | Mot de passe de l'utilisateur |

.3+| *Geoserver*
| GEOSERVER_URL | Url de Geoserver | http://localhost:8090/geoserver
| GEOSERVER_USER | Utilisateur de connexion à Geoserver |
| GEOSERVER_PASSWORD | Mot de passe de l'utilisateur |

.1+| *Autre*
| DOCKER_REMOCRA_VERSION | Numéro de version de REMOcRA à installer |
|===

=== Modification de la bannière keycloak pour le logo du SDIS

La personalisation de la bannière pour la mire de connexion sous keycloak se fait via le volume docker `/var/lib/remocra/images/ressources:/opt/keycloak/themes/remocra/login/resources/img:ro`.

L'image est donc à déposer sur le serveur dans le dossier `/var/lib/remocra/images/ressources` et doit obligatoirement s'appeler `banniere`

=== Création d’un utilisateur REMOcRA

Un utilisateur _remocra_ est nécessaire. Voici les commandes à exécuter :
[source,console]
----
groupadd -g 2000 remocra
useradd -u 2000 -g remocra remocra
----

=== Création de dossiers

Créer les dossiers suivants et leur affecter tous deux les droits _remocra_ :

[source,console]
----
mkdir /var/log/remocra
mkdir /var/lib/remocra
mkdir /var/opt/geoserver
# mdkir /var/opt/apache-hop # si Apache Hop est installé

chown -R remocra: /var/lib/remocra
chown -R remocra: /var/log/remocra
chown -R remocra: /var/opt/geoserver
# chown -R remocra: /var/opt/apache-hop # si Apache Hop est installé
----

=== Démarrer les images

Il faut préalablement s'authentifier auprès du registry docker pour pouvoir télécharger les images :

[source, console]
----
docker login client-docker-registry.atolcd.com
----

Lancer les commandes suivantes. Elles permettront de télécharger les images et de démarrer les différents conteneurs nécessaires au projet.

[source,console]
----
cd /opt/remocra/

# Passage des patchs de base de données
docker compose run --rm remocra migrate-db

docker compose up -d
----

NOTE: Sans application des patchs de base de données l'application ne peut pas démarrer.

=== Configuration de keycloak

==== Création de l'utilisateur super-admin

On va déjà créer un utilisateur super-admin temporaire via la commande suivante :
[source,console]
----
docker compose run --rm \
    -e KEYCLOAK_URL=http://localhost:8080 \
    -e USERNAME=<tmp_username> \
    -e PASSWORD=<tmp_password> \
    keycloak bootstrap-admin user --username:env USERNAME --password:env PASSWORD --no-prompt
----

Puis créer l'utilisateur super-admin définitif :
[source,console]
----
docker compose run --rm \
    -e KEYCLOAK_URL=http://localhost:8080 \
    -e KEYCLOAK_USER=<tmp_username> \
    -e KEYCLOAK_PASSWORD=<tmp_password> \
    keycloak kcadm.sh create users -r master -s username=<super_username> -s enabled=true
----

Initialise son mot de passe:
[source,console]
----
docker compose run --rm \
    -e KEYCLOAK_URL=http://localhost:8080 \
    -e KEYCLOAK_USER=<tmp_username> \
    -e KEYCLOAK_PASSWORD=<tmp_password> \
    keycloak kcadm.sh set-password -r master --username <super_username> --new-password <super_password>
----

Puis lui affecter le rôle pour qu'il soit super-admin :
[source,console]
----
docker compose run --rm \
    -e KEYCLOAK_URL=http://localhost:8080 \
    -e KEYCLOAK_USER=<tmp_username> \
    -e KEYCLOAK_PASSWORD=<tmp_password> \
    keycloak kcadm.sh add-roles -r master --uusername super_username --rolename admin
----

On peut maintenant se connecter avec l'utilisateur nouvellement créer.

WARNING: Vérifié que le compte créé fonctionne correctement en se connectant à l'admin keycloak.

Derniére étape : supprimer le compte temporaire :
[source,console]
----
USER_ID=$(docker compose run --rm \
    -e KEYCLOAK_URL=http://localhost:8080 \
    -e KEYCLOAK_USER=<super_username> \
    -e KEYCLOAK_PASSWORD=<super_password> \
    keycloak kcadm.sh get users -r master -q username=<tmp_username> --fields id --format csv --noquotes) && \
docker compose run --rm \
    -e KEYCLOAK_URL=http://localhost:8080 \
    -e KEYCLOAK_USER=<super_username> \
    -e KEYCLOAK_PASSWORD=<super_password> \
    keycloak kcadm.sh delete users/$USER_ID -r master
----

===== Script de création du super utilisateur

[source,bash]
----
include::keycloak_create_super_admin.sh[]
----

==== Création et configuration du realm remocra

Pour finir la configuration de keycloak, exécutez la commande suivante :
[source,console]
----
docker compose run --rm \
    -e KEYCLOAK_URL=http://localhost:8080 \
    -e KEYCLOAK_USER=<super_username> \
    -e KEYCLOAK_PASSWORD=<super_password> \
    keycloak keycloak-config-cli
----

NOTE: Le couple super_username/super_password est celui créer à l'étape précédente.
