/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.locationtech.jts.geom.Geometry
import remocra.db.jooq.bindings.GeometryBinding
import remocra.db.jooq.bindings.ZonedDateTimeBinding
import remocra.db.jooq.entrepotsig.Entrepotsig
import remocra.db.jooq.remocra.enums.TypeAire
import java.time.ZonedDateTime
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class VDfciAireSig(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Entrepotsig.ENTREPOTSIG,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view(
        """
    CREATE VIEW "v_dfci_aire_sig" AS  SELECT dfci_aire_id AS v_dfci_aire_sig_id,
     dfci_aire_amenagement AS v_dfci_aire_sig_amenagement,
     dfci_aire_date_gps AS v_dfci_aire_sig_date_gps,
     dfci_aire_grande_dimension AS v_dfci_aire_sig_grande_dimension,
     dfci_aire_petite_dimension AS v_dfci_aire_sig_petite_dimension,
     dfci_aire_type AS v_dfci_aire_sig_type,
     dfci_aire_dfci_piste_id AS v_dfci_aire_sig_dfci_piste_id,
     dfci_aire_remarque AS v_dfci_aire_sig_remarque,
     dfci_aire_geometrie AS v_dfci_aire_sig_geometrie,
     dfci_aire_code AS v_dfci_aire_sig_code,
     dfci_aire_version AS v_dfci_aire_sig_version
    FROM dfci_aire;
    """,
    ),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>entrepotsig.v_dfci_aire_sig</code>
         */
        val V_DFCI_AIRE_SIG: VDfciAireSig = VDfciAireSig()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("v_dfci_aire_sig_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_amenagement</code>.
     */
    val AMENAGEMENT: TableField<Record, Boolean?> = createField(DSL.name("v_dfci_aire_sig_amenagement"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_date_gps</code>.
     */
    val DATE_GPS: TableField<Record, ZonedDateTime?> = createField(DSL.name("v_dfci_aire_sig_date_gps"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", ZonedDateTimeBinding())

    /**
     * The column
     * <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_grande_dimension</code>.
     */
    val GRANDE_DIMENSION: TableField<Record, Double?> = createField(DSL.name("v_dfci_aire_sig_grande_dimension"), SQLDataType.DOUBLE, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_petite_dimension</code>.
     */
    val PETITE_DIMENSION: TableField<Record, Double?> = createField(DSL.name("v_dfci_aire_sig_petite_dimension"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_type</code>.
     */
    val TYPE: TableField<Record, TypeAire?> = createField(DSL.name("v_dfci_aire_sig_type"), SQLDataType.VARCHAR.asEnumDataType(TypeAire::class.java), this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_dfci_piste_id</code>.
     */
    val DFCI_PISTE_ID: TableField<Record, UUID?> = createField(DSL.name("v_dfci_aire_sig_dfci_piste_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_remarque</code>.
     */
    val REMARQUE: TableField<Record, String?> = createField(DSL.name("v_dfci_aire_sig_remarque"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_geometrie</code>.
     */
    val GEOMETRIE: TableField<Record, Geometry?> = createField(DSL.name("v_dfci_aire_sig_geometrie"), SQLDataType.GEOMETRY, this, "", GeometryBinding())

    /**
     * The column <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_code</code>.
     */
    val CODE: TableField<Record, String?> = createField(DSL.name("v_dfci_aire_sig_code"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_aire_sig.v_dfci_aire_sig_version</code>.
     */
    val VERSION: TableField<Record, Int?> = createField(DSL.name("v_dfci_aire_sig_version"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>entrepotsig.v_dfci_aire_sig</code> table
     * reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>entrepotsig.v_dfci_aire_sig</code> table
     * reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>entrepotsig.v_dfci_aire_sig</code> table reference
     */
    constructor() : this(DSL.name("v_dfci_aire_sig"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Entrepotsig.ENTREPOTSIG
    override fun `as`(alias: String): VDfciAireSig = VDfciAireSig(DSL.name(alias), this)
    override fun `as`(alias: Name): VDfciAireSig = VDfciAireSig(alias, this)
    override fun `as`(alias: Table<*>): VDfciAireSig = VDfciAireSig(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VDfciAireSig = VDfciAireSig(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VDfciAireSig = VDfciAireSig(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VDfciAireSig = VDfciAireSig(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VDfciAireSig = VDfciAireSig(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VDfciAireSig = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VDfciAireSig = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VDfciAireSig = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VDfciAireSig = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VDfciAireSig = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VDfciAireSig = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VDfciAireSig = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VDfciAireSig = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VDfciAireSig = where(DSL.notExists(select))
}
