/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig.tables

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.locationtech.jts.geom.Geometry
import remocra.db.jooq.bindings.GeometryBinding
import remocra.db.jooq.bindings.ZonedDateTimeBinding
import remocra.db.jooq.entrepotsig.Entrepotsig
import remocra.db.jooq.remocra.enums.TypeCroisement
import remocra.db.jooq.remocra.enums.TypeFoncier
import remocra.db.jooq.remocra.enums.TypeImpasse
import remocra.db.jooq.remocra.enums.TypeImpraticabilite
import remocra.db.jooq.remocra.enums.TypeProgramme
import remocra.db.jooq.remocra.enums.TypeTravaux
import remocra.db.jooq.remocra.enums.TypeVoie
import java.time.ZonedDateTime
import java.util.UUID
import javax.annotation.processing.Generated
import kotlin.collections.Collection

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
open class VDfciPisteSig(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<Record>(
    alias,
    Entrepotsig.ENTREPOTSIG,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.view(
        """
    CREATE VIEW "v_dfci_piste_sig" AS  SELECT dfci_piste_id AS v_dfci_piste_sig_id,
     dfci_piste_adresse AS v_dfci_piste_sig_adresse,
     dfci_piste_annee_programme AS v_dfci_piste_sig_annee_programme,
     dfci_piste_annee_travaux AS v_dfci_piste_sig_annee_travaux,
     dfci_piste_circulation AS v_dfci_piste_sig_circulation,
     dfci_piste_date_gps AS v_dfci_piste_sig_date_gps,
     dfci_piste_libelle AS v_dfci_piste_sig_libelle,
     dfci_piste_numero AS v_dfci_piste_sig_numero,
     dfci_piste_ouverture AS v_dfci_piste_sig_ouverture,
     dfci_piste_est_dfci AS v_dfci_piste_sig_est_dfci,
     dfci_piste_retournement AS v_dfci_piste_sig_retournement,
     dfci_piste_num_troncon AS v_dfci_piste_sig_num_troncon,
     dfci_piste_num_objectif AS v_dfci_piste_sig_num_objectif,
     dfci_piste_libelle_objectif AS v_dfci_piste_sig_libelle_objectif,
     dfci_piste_geometrie AS v_dfci_piste_sig_geometrie,
     dfci_piste_impraticabilite AS v_dfci_piste_sig_impraticabilite,
     dfci_piste_travaux AS v_dfci_piste_sig_travaux,
     dfci_piste_voie AS v_dfci_piste_sig_voie,
     dfci_piste_impasse AS v_dfci_piste_sig_impasse,
     dfci_piste_foncier AS v_dfci_piste_sig_foncier,
     dfci_piste_croisement AS v_dfci_piste_sig_croisement,
     dfci_piste_programme AS v_dfci_piste_sig_programme,
     dfci_piste_praticabilite AS v_dfci_piste_sig_praticabilite,
     dfci_piste_remarque AS v_dfci_piste_sig_remarque,
     dfci_piste_code AS v_dfci_piste_sig_code,
     dfci_piste_dfci_categorie_piste_id AS v_dfci_piste_sig_dfci_categorie_piste_id,
     dfci_piste_dfci_massif_id AS v_dfci_piste_sig_dfci_massif_id,
     dfci_piste_dfci_prestataire_id AS v_dfci_piste_sig_dfci_prestataire_id,
     dfci_piste_dfci_ouvrage_id AS v_dfci_piste_sig_dfci_ouvrage_id,
     dfci_piste_version AS v_dfci_piste_sig_version
    FROM dfci_piste;
    """,
    ),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>entrepotsig.v_dfci_piste_sig</code>
         */
        val V_DFCI_PISTE_SIG: VDfciPisteSig = VDfciPisteSig()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Record> = Record::class.java

    /**
     * The column <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_id</code>.
     */
    val ID: TableField<Record, UUID?> = createField(DSL.name("v_dfci_piste_sig_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_adresse</code>.
     */
    val ADRESSE: TableField<Record, String?> = createField(DSL.name("v_dfci_piste_sig_adresse"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_annee_programme</code>.
     */
    val ANNEE_PROGRAMME: TableField<Record, Int?> = createField(DSL.name("v_dfci_piste_sig_annee_programme"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_annee_travaux</code>.
     */
    val ANNEE_TRAVAUX: TableField<Record, Int?> = createField(DSL.name("v_dfci_piste_sig_annee_travaux"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_circulation</code>.
     */
    val CIRCULATION: TableField<Record, Boolean?> = createField(DSL.name("v_dfci_piste_sig_circulation"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_date_gps</code>.
     */
    val DATE_GPS: TableField<Record, ZonedDateTime?> = createField(DSL.name("v_dfci_piste_sig_date_gps"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", ZonedDateTimeBinding())

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_libelle</code>.
     */
    val LIBELLE: TableField<Record, String?> = createField(DSL.name("v_dfci_piste_sig_libelle"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_numero</code>.
     */
    val NUMERO: TableField<Record, String?> = createField(DSL.name("v_dfci_piste_sig_numero"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_ouverture</code>.
     */
    val OUVERTURE: TableField<Record, Boolean?> = createField(DSL.name("v_dfci_piste_sig_ouverture"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_est_dfci</code>.
     */
    val EST_DFCI: TableField<Record, Boolean?> = createField(DSL.name("v_dfci_piste_sig_est_dfci"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_retournement</code>.
     */
    val RETOURNEMENT: TableField<Record, Boolean?> = createField(DSL.name("v_dfci_piste_sig_retournement"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_num_troncon</code>.
     */
    val NUM_TRONCON: TableField<Record, Int?> = createField(DSL.name("v_dfci_piste_sig_num_troncon"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_num_objectif</code>.
     */
    val NUM_OBJECTIF: TableField<Record, Int?> = createField(DSL.name("v_dfci_piste_sig_num_objectif"), SQLDataType.INTEGER, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_libelle_objectif</code>.
     */
    val LIBELLE_OBJECTIF: TableField<Record, String?> = createField(DSL.name("v_dfci_piste_sig_libelle_objectif"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_geometrie</code>.
     */
    val GEOMETRIE: TableField<Record, Geometry?> = createField(DSL.name("v_dfci_piste_sig_geometrie"), SQLDataType.GEOMETRY, this, "", GeometryBinding())

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_impraticabilite</code>.
     */
    val IMPRATICABILITE: TableField<Record, TypeImpraticabilite?> = createField(DSL.name("v_dfci_piste_sig_impraticabilite"), SQLDataType.VARCHAR.asEnumDataType(TypeImpraticabilite::class.java), this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_travaux</code>.
     */
    val TRAVAUX: TableField<Record, TypeTravaux?> = createField(DSL.name("v_dfci_piste_sig_travaux"), SQLDataType.VARCHAR.asEnumDataType(TypeTravaux::class.java), this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_voie</code>.
     */
    val VOIE: TableField<Record, TypeVoie?> = createField(DSL.name("v_dfci_piste_sig_voie"), SQLDataType.VARCHAR.asEnumDataType(TypeVoie::class.java), this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_impasse</code>.
     */
    val IMPASSE: TableField<Record, TypeImpasse?> = createField(DSL.name("v_dfci_piste_sig_impasse"), SQLDataType.VARCHAR.asEnumDataType(TypeImpasse::class.java), this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_foncier</code>.
     */
    val FONCIER: TableField<Record, TypeFoncier?> = createField(DSL.name("v_dfci_piste_sig_foncier"), SQLDataType.VARCHAR.asEnumDataType(TypeFoncier::class.java), this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_croisement</code>.
     */
    val CROISEMENT: TableField<Record, TypeCroisement?> = createField(DSL.name("v_dfci_piste_sig_croisement"), SQLDataType.VARCHAR.asEnumDataType(TypeCroisement::class.java), this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_programme</code>.
     */
    val PROGRAMME: TableField<Record, TypeProgramme?> = createField(DSL.name("v_dfci_piste_sig_programme"), SQLDataType.VARCHAR.asEnumDataType(TypeProgramme::class.java), this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_praticabilite</code>.
     */
    val PRATICABILITE: TableField<Record, Boolean?> = createField(DSL.name("v_dfci_piste_sig_praticabilite"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_remarque</code>.
     */
    val REMARQUE: TableField<Record, String?> = createField(DSL.name("v_dfci_piste_sig_remarque"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_code</code>.
     */
    val CODE: TableField<Record, String?> = createField(DSL.name("v_dfci_piste_sig_code"), SQLDataType.CLOB, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_dfci_categorie_piste_id</code>.
     */
    val DFCI_CATEGORIE_PISTE_ID: TableField<Record, UUID?> = createField(DSL.name("v_dfci_piste_sig_dfci_categorie_piste_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_dfci_massif_id</code>.
     */
    val DFCI_MASSIF_ID: TableField<Record, UUID?> = createField(DSL.name("v_dfci_piste_sig_dfci_massif_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_dfci_prestataire_id</code>.
     */
    val DFCI_PRESTATAIRE_ID: TableField<Record, UUID?> = createField(DSL.name("v_dfci_piste_sig_dfci_prestataire_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_dfci_ouvrage_id</code>.
     */
    val DFCI_OUVRAGE_ID: TableField<Record, UUID?> = createField(DSL.name("v_dfci_piste_sig_dfci_ouvrage_id"), SQLDataType.UUID, this, "")

    /**
     * The column
     * <code>entrepotsig.v_dfci_piste_sig.v_dfci_piste_sig_version</code>.
     */
    val VERSION: TableField<Record, Int?> = createField(DSL.name("v_dfci_piste_sig_version"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<Record>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>entrepotsig.v_dfci_piste_sig</code> table
     * reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>entrepotsig.v_dfci_piste_sig</code> table
     * reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>entrepotsig.v_dfci_piste_sig</code> table reference
     */
    constructor() : this(DSL.name("v_dfci_piste_sig"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Entrepotsig.ENTREPOTSIG
    override fun `as`(alias: String): VDfciPisteSig = VDfciPisteSig(DSL.name(alias), this)
    override fun `as`(alias: Name): VDfciPisteSig = VDfciPisteSig(alias, this)
    override fun `as`(alias: Table<*>): VDfciPisteSig = VDfciPisteSig(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VDfciPisteSig = VDfciPisteSig(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VDfciPisteSig = VDfciPisteSig(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VDfciPisteSig = VDfciPisteSig(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VDfciPisteSig = VDfciPisteSig(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VDfciPisteSig = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VDfciPisteSig = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VDfciPisteSig = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VDfciPisteSig = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VDfciPisteSig = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VDfciPisteSig = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VDfciPisteSig = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VDfciPisteSig = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VDfciPisteSig = where(DSL.notExists(select))
}
