/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig.tables.pojos

import org.locationtech.jts.geom.Geometry
import remocra.db.jooq.remocra.enums.TypeDebroussaillement
import remocra.db.jooq.remocra.enums.TypeProgramme
import remocra.db.jooq.remocra.enums.TypeTravaux
import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class VDfciDebSig(
    val vDfciDebSigId: UUID?,
    val vDfciDebSigLibelle: String?,
    val vDfciDebSigAnneeProgramme: Int?,
    val vDfciDebSigAnneeTravaux: Int?,
    val vDfciDebSigMoisTravaux: Int?,
    val vDfciDebSigAnneeEdition: Int?,
    val vDfciDebSigLargeur: Double?,
    val vDfciDebSigSurface: Double?,
    val vDfciDebSigGeometrie: Geometry?,
    val vDfciDebSigType: TypeDebroussaillement?,
    val vDfciDebSigProgramme: TypeProgramme?,
    val vDfciDebSigTravaux: TypeTravaux?,
    val vDfciDebSigRemarque: String?,
    val vDfciDebSigCode: String?,
    val vDfciDebSigDfciMassifId: UUID?,
    val vDfciDebSigDfciPrestataireId: UUID?,
    val vDfciDebSigDfciOuvrageId: UUID?,
    val vDfciDebSigVersion: Int?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: VDfciDebSig = other as VDfciDebSig
        if (this.vDfciDebSigId == null) {
            if (o.vDfciDebSigId != null) {
                return false
            }
        } else if (this.vDfciDebSigId != o.vDfciDebSigId) {
            return false
        }
        if (this.vDfciDebSigLibelle == null) {
            if (o.vDfciDebSigLibelle != null) {
                return false
            }
        } else if (this.vDfciDebSigLibelle != o.vDfciDebSigLibelle) {
            return false
        }
        if (this.vDfciDebSigAnneeProgramme == null) {
            if (o.vDfciDebSigAnneeProgramme != null) {
                return false
            }
        } else if (this.vDfciDebSigAnneeProgramme != o.vDfciDebSigAnneeProgramme) {
            return false
        }
        if (this.vDfciDebSigAnneeTravaux == null) {
            if (o.vDfciDebSigAnneeTravaux != null) {
                return false
            }
        } else if (this.vDfciDebSigAnneeTravaux != o.vDfciDebSigAnneeTravaux) {
            return false
        }
        if (this.vDfciDebSigMoisTravaux == null) {
            if (o.vDfciDebSigMoisTravaux != null) {
                return false
            }
        } else if (this.vDfciDebSigMoisTravaux != o.vDfciDebSigMoisTravaux) {
            return false
        }
        if (this.vDfciDebSigAnneeEdition == null) {
            if (o.vDfciDebSigAnneeEdition != null) {
                return false
            }
        } else if (this.vDfciDebSigAnneeEdition != o.vDfciDebSigAnneeEdition) {
            return false
        }
        if (this.vDfciDebSigLargeur == null) {
            if (o.vDfciDebSigLargeur != null) {
                return false
            }
        } else if (this.vDfciDebSigLargeur != o.vDfciDebSigLargeur) {
            return false
        }
        if (this.vDfciDebSigSurface == null) {
            if (o.vDfciDebSigSurface != null) {
                return false
            }
        } else if (this.vDfciDebSigSurface != o.vDfciDebSigSurface) {
            return false
        }
        if (this.vDfciDebSigGeometrie == null) {
            if (o.vDfciDebSigGeometrie != null) {
                return false
            }
        } else if (this.vDfciDebSigGeometrie != o.vDfciDebSigGeometrie) {
            return false
        }
        if (this.vDfciDebSigType == null) {
            if (o.vDfciDebSigType != null) {
                return false
            }
        } else if (this.vDfciDebSigType != o.vDfciDebSigType) {
            return false
        }
        if (this.vDfciDebSigProgramme == null) {
            if (o.vDfciDebSigProgramme != null) {
                return false
            }
        } else if (this.vDfciDebSigProgramme != o.vDfciDebSigProgramme) {
            return false
        }
        if (this.vDfciDebSigTravaux == null) {
            if (o.vDfciDebSigTravaux != null) {
                return false
            }
        } else if (this.vDfciDebSigTravaux != o.vDfciDebSigTravaux) {
            return false
        }
        if (this.vDfciDebSigRemarque == null) {
            if (o.vDfciDebSigRemarque != null) {
                return false
            }
        } else if (this.vDfciDebSigRemarque != o.vDfciDebSigRemarque) {
            return false
        }
        if (this.vDfciDebSigCode == null) {
            if (o.vDfciDebSigCode != null) {
                return false
            }
        } else if (this.vDfciDebSigCode != o.vDfciDebSigCode) {
            return false
        }
        if (this.vDfciDebSigDfciMassifId == null) {
            if (o.vDfciDebSigDfciMassifId != null) {
                return false
            }
        } else if (this.vDfciDebSigDfciMassifId != o.vDfciDebSigDfciMassifId) {
            return false
        }
        if (this.vDfciDebSigDfciPrestataireId == null) {
            if (o.vDfciDebSigDfciPrestataireId != null) {
                return false
            }
        } else if (this.vDfciDebSigDfciPrestataireId != o.vDfciDebSigDfciPrestataireId) {
            return false
        }
        if (this.vDfciDebSigDfciOuvrageId == null) {
            if (o.vDfciDebSigDfciOuvrageId != null) {
                return false
            }
        } else if (this.vDfciDebSigDfciOuvrageId != o.vDfciDebSigDfciOuvrageId) {
            return false
        }
        if (this.vDfciDebSigVersion == null) {
            if (o.vDfciDebSigVersion != null) {
                return false
            }
        } else if (this.vDfciDebSigVersion != o.vDfciDebSigVersion) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.vDfciDebSigId == null) 0 else this.vDfciDebSigId.hashCode())
        result = prime * result + (if (this.vDfciDebSigLibelle == null) 0 else this.vDfciDebSigLibelle.hashCode())
        result = prime * result + (if (this.vDfciDebSigAnneeProgramme == null) 0 else this.vDfciDebSigAnneeProgramme.hashCode())
        result = prime * result + (if (this.vDfciDebSigAnneeTravaux == null) 0 else this.vDfciDebSigAnneeTravaux.hashCode())
        result = prime * result + (if (this.vDfciDebSigMoisTravaux == null) 0 else this.vDfciDebSigMoisTravaux.hashCode())
        result = prime * result + (if (this.vDfciDebSigAnneeEdition == null) 0 else this.vDfciDebSigAnneeEdition.hashCode())
        result = prime * result + (if (this.vDfciDebSigLargeur == null) 0 else this.vDfciDebSigLargeur.hashCode())
        result = prime * result + (if (this.vDfciDebSigSurface == null) 0 else this.vDfciDebSigSurface.hashCode())
        result = prime * result + (if (this.vDfciDebSigGeometrie == null) 0 else this.vDfciDebSigGeometrie.hashCode())
        result = prime * result + (if (this.vDfciDebSigType == null) 0 else this.vDfciDebSigType.hashCode())
        result = prime * result + (if (this.vDfciDebSigProgramme == null) 0 else this.vDfciDebSigProgramme.hashCode())
        result = prime * result + (if (this.vDfciDebSigTravaux == null) 0 else this.vDfciDebSigTravaux.hashCode())
        result = prime * result + (if (this.vDfciDebSigRemarque == null) 0 else this.vDfciDebSigRemarque.hashCode())
        result = prime * result + (if (this.vDfciDebSigCode == null) 0 else this.vDfciDebSigCode.hashCode())
        result = prime * result + (if (this.vDfciDebSigDfciMassifId == null) 0 else this.vDfciDebSigDfciMassifId.hashCode())
        result = prime * result + (if (this.vDfciDebSigDfciPrestataireId == null) 0 else this.vDfciDebSigDfciPrestataireId.hashCode())
        result = prime * result + (if (this.vDfciDebSigDfciOuvrageId == null) 0 else this.vDfciDebSigDfciOuvrageId.hashCode())
        result = prime * result + (if (this.vDfciDebSigVersion == null) 0 else this.vDfciDebSigVersion.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VDfciDebSig (")

        sb.append(vDfciDebSigId)
        sb.append(", ").append(vDfciDebSigLibelle)
        sb.append(", ").append(vDfciDebSigAnneeProgramme)
        sb.append(", ").append(vDfciDebSigAnneeTravaux)
        sb.append(", ").append(vDfciDebSigMoisTravaux)
        sb.append(", ").append(vDfciDebSigAnneeEdition)
        sb.append(", ").append(vDfciDebSigLargeur)
        sb.append(", ").append(vDfciDebSigSurface)
        sb.append(", ").append(vDfciDebSigGeometrie)
        sb.append(", ").append(vDfciDebSigType)
        sb.append(", ").append(vDfciDebSigProgramme)
        sb.append(", ").append(vDfciDebSigTravaux)
        sb.append(", ").append(vDfciDebSigRemarque)
        sb.append(", ").append(vDfciDebSigCode)
        sb.append(", ").append(vDfciDebSigDfciMassifId)
        sb.append(", ").append(vDfciDebSigDfciPrestataireId)
        sb.append(", ").append(vDfciDebSigDfciOuvrageId)
        sb.append(", ").append(vDfciDebSigVersion)

        sb.append(")")
        return sb.toString()
    }
}
