/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class VDfciCategoriePisteSig(
    val vDfciCategoriePisteSigId: UUID?,
    val vDfciCategoriePisteSigCode: String?,
    val vDfciCategoriePisteSigLibelle: String?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: VDfciCategoriePisteSig = other as VDfciCategoriePisteSig
        if (this.vDfciCategoriePisteSigId == null) {
            if (o.vDfciCategoriePisteSigId != null) {
                return false
            }
        } else if (this.vDfciCategoriePisteSigId != o.vDfciCategoriePisteSigId) {
            return false
        }
        if (this.vDfciCategoriePisteSigCode == null) {
            if (o.vDfciCategoriePisteSigCode != null) {
                return false
            }
        } else if (this.vDfciCategoriePisteSigCode != o.vDfciCategoriePisteSigCode) {
            return false
        }
        if (this.vDfciCategoriePisteSigLibelle == null) {
            if (o.vDfciCategoriePisteSigLibelle != null) {
                return false
            }
        } else if (this.vDfciCategoriePisteSigLibelle != o.vDfciCategoriePisteSigLibelle) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.vDfciCategoriePisteSigId == null) 0 else this.vDfciCategoriePisteSigId.hashCode())
        result = prime * result + (if (this.vDfciCategoriePisteSigCode == null) 0 else this.vDfciCategoriePisteSigCode.hashCode())
        result = prime * result + (if (this.vDfciCategoriePisteSigLibelle == null) 0 else this.vDfciCategoriePisteSigLibelle.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VDfciCategoriePisteSig (")

        sb.append(vDfciCategoriePisteSigId)
        sb.append(", ").append(vDfciCategoriePisteSigCode)
        sb.append(", ").append(vDfciCategoriePisteSigLibelle)

        sb.append(")")
        return sb.toString()
    }
}
