/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig.tables.pojos

import org.locationtech.jts.geom.Geometry
import remocra.db.jooq.remocra.enums.TypeAire
import java.io.Serializable
import java.time.ZonedDateTime
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class VDfciAireSig(
    val vDfciAireSigId: UUID?,
    val vDfciAireSigAmenagement: Boolean?,
    val vDfciAireSigDateGps: ZonedDateTime?,
    val vDfciAireSigGrandeDimension: Double?,
    val vDfciAireSigPetiteDimension: Double?,
    val vDfciAireSigType: TypeAire?,
    val vDfciAireSigDfciPisteId: UUID?,
    val vDfciAireSigRemarque: String?,
    val vDfciAireSigGeometrie: Geometry?,
    val vDfciAireSigCode: String?,
    val vDfciAireSigVersion: Int?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: VDfciAireSig = other as VDfciAireSig
        if (this.vDfciAireSigId == null) {
            if (o.vDfciAireSigId != null) {
                return false
            }
        } else if (this.vDfciAireSigId != o.vDfciAireSigId) {
            return false
        }
        if (this.vDfciAireSigAmenagement == null) {
            if (o.vDfciAireSigAmenagement != null) {
                return false
            }
        } else if (this.vDfciAireSigAmenagement != o.vDfciAireSigAmenagement) {
            return false
        }
        if (this.vDfciAireSigDateGps == null) {
            if (o.vDfciAireSigDateGps != null) {
                return false
            }
        } else if (this.vDfciAireSigDateGps != o.vDfciAireSigDateGps) {
            return false
        }
        if (this.vDfciAireSigGrandeDimension == null) {
            if (o.vDfciAireSigGrandeDimension != null) {
                return false
            }
        } else if (this.vDfciAireSigGrandeDimension != o.vDfciAireSigGrandeDimension) {
            return false
        }
        if (this.vDfciAireSigPetiteDimension == null) {
            if (o.vDfciAireSigPetiteDimension != null) {
                return false
            }
        } else if (this.vDfciAireSigPetiteDimension != o.vDfciAireSigPetiteDimension) {
            return false
        }
        if (this.vDfciAireSigType == null) {
            if (o.vDfciAireSigType != null) {
                return false
            }
        } else if (this.vDfciAireSigType != o.vDfciAireSigType) {
            return false
        }
        if (this.vDfciAireSigDfciPisteId == null) {
            if (o.vDfciAireSigDfciPisteId != null) {
                return false
            }
        } else if (this.vDfciAireSigDfciPisteId != o.vDfciAireSigDfciPisteId) {
            return false
        }
        if (this.vDfciAireSigRemarque == null) {
            if (o.vDfciAireSigRemarque != null) {
                return false
            }
        } else if (this.vDfciAireSigRemarque != o.vDfciAireSigRemarque) {
            return false
        }
        if (this.vDfciAireSigGeometrie == null) {
            if (o.vDfciAireSigGeometrie != null) {
                return false
            }
        } else if (this.vDfciAireSigGeometrie != o.vDfciAireSigGeometrie) {
            return false
        }
        if (this.vDfciAireSigCode == null) {
            if (o.vDfciAireSigCode != null) {
                return false
            }
        } else if (this.vDfciAireSigCode != o.vDfciAireSigCode) {
            return false
        }
        if (this.vDfciAireSigVersion == null) {
            if (o.vDfciAireSigVersion != null) {
                return false
            }
        } else if (this.vDfciAireSigVersion != o.vDfciAireSigVersion) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.vDfciAireSigId == null) 0 else this.vDfciAireSigId.hashCode())
        result = prime * result + (if (this.vDfciAireSigAmenagement == null) 0 else this.vDfciAireSigAmenagement.hashCode())
        result = prime * result + (if (this.vDfciAireSigDateGps == null) 0 else this.vDfciAireSigDateGps.hashCode())
        result = prime * result + (if (this.vDfciAireSigGrandeDimension == null) 0 else this.vDfciAireSigGrandeDimension.hashCode())
        result = prime * result + (if (this.vDfciAireSigPetiteDimension == null) 0 else this.vDfciAireSigPetiteDimension.hashCode())
        result = prime * result + (if (this.vDfciAireSigType == null) 0 else this.vDfciAireSigType.hashCode())
        result = prime * result + (if (this.vDfciAireSigDfciPisteId == null) 0 else this.vDfciAireSigDfciPisteId.hashCode())
        result = prime * result + (if (this.vDfciAireSigRemarque == null) 0 else this.vDfciAireSigRemarque.hashCode())
        result = prime * result + (if (this.vDfciAireSigGeometrie == null) 0 else this.vDfciAireSigGeometrie.hashCode())
        result = prime * result + (if (this.vDfciAireSigCode == null) 0 else this.vDfciAireSigCode.hashCode())
        result = prime * result + (if (this.vDfciAireSigVersion == null) 0 else this.vDfciAireSigVersion.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VDfciAireSig (")

        sb.append(vDfciAireSigId)
        sb.append(", ").append(vDfciAireSigAmenagement)
        sb.append(", ").append(vDfciAireSigDateGps)
        sb.append(", ").append(vDfciAireSigGrandeDimension)
        sb.append(", ").append(vDfciAireSigPetiteDimension)
        sb.append(", ").append(vDfciAireSigType)
        sb.append(", ").append(vDfciAireSigDfciPisteId)
        sb.append(", ").append(vDfciAireSigRemarque)
        sb.append(", ").append(vDfciAireSigGeometrie)
        sb.append(", ").append(vDfciAireSigCode)
        sb.append(", ").append(vDfciAireSigVersion)

        sb.append(")")
        return sb.toString()
    }
}
