/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class VDfciPrestataireSig(
    val vDfciPrestataireSigId: UUID?,
    val vDfciPrestataireSigCode: String?,
    val vDfciPrestataireSigLibelle: String?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: VDfciPrestataireSig = other as VDfciPrestataireSig
        if (this.vDfciPrestataireSigId == null) {
            if (o.vDfciPrestataireSigId != null) {
                return false
            }
        } else if (this.vDfciPrestataireSigId != o.vDfciPrestataireSigId) {
            return false
        }
        if (this.vDfciPrestataireSigCode == null) {
            if (o.vDfciPrestataireSigCode != null) {
                return false
            }
        } else if (this.vDfciPrestataireSigCode != o.vDfciPrestataireSigCode) {
            return false
        }
        if (this.vDfciPrestataireSigLibelle == null) {
            if (o.vDfciPrestataireSigLibelle != null) {
                return false
            }
        } else if (this.vDfciPrestataireSigLibelle != o.vDfciPrestataireSigLibelle) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.vDfciPrestataireSigId == null) 0 else this.vDfciPrestataireSigId.hashCode())
        result = prime * result + (if (this.vDfciPrestataireSigCode == null) 0 else this.vDfciPrestataireSigCode.hashCode())
        result = prime * result + (if (this.vDfciPrestataireSigLibelle == null) 0 else this.vDfciPrestataireSigLibelle.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VDfciPrestataireSig (")

        sb.append(vDfciPrestataireSigId)
        sb.append(", ").append(vDfciPrestataireSigCode)
        sb.append(", ").append(vDfciPrestataireSigLibelle)

        sb.append(")")
        return sb.toString()
    }
}
