/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig.tables.pojos

import java.io.Serializable
import java.util.UUID
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
data class VDfciOuvrageSig(
    val vDfciOuvrageSigId: UUID?,
    val vDfciOuvrageSigCode: String?,
    val vDfciOuvrageSigLibelle: String?,
) : Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (other == null) {
            return false
        }
        if (this::class != other::class) {
            return false
        }
        val o: VDfciOuvrageSig = other as VDfciOuvrageSig
        if (this.vDfciOuvrageSigId == null) {
            if (o.vDfciOuvrageSigId != null) {
                return false
            }
        } else if (this.vDfciOuvrageSigId != o.vDfciOuvrageSigId) {
            return false
        }
        if (this.vDfciOuvrageSigCode == null) {
            if (o.vDfciOuvrageSigCode != null) {
                return false
            }
        } else if (this.vDfciOuvrageSigCode != o.vDfciOuvrageSigCode) {
            return false
        }
        if (this.vDfciOuvrageSigLibelle == null) {
            if (o.vDfciOuvrageSigLibelle != null) {
                return false
            }
        } else if (this.vDfciOuvrageSigLibelle != o.vDfciOuvrageSigLibelle) {
            return false
        }
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.vDfciOuvrageSigId == null) 0 else this.vDfciOuvrageSigId.hashCode())
        result = prime * result + (if (this.vDfciOuvrageSigCode == null) 0 else this.vDfciOuvrageSigCode.hashCode())
        result = prime * result + (if (this.vDfciOuvrageSigLibelle == null) 0 else this.vDfciOuvrageSigLibelle.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VDfciOuvrageSig (")

        sb.append(vDfciOuvrageSigId)
        sb.append(", ").append(vDfciOuvrageSigCode)
        sb.append(", ").append(vDfciOuvrageSigLibelle)

        sb.append(")")
        return sb.toString()
    }
}
