@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */

package remocra.db.jooq.historique.keys

import org.jooq.Record
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import remocra.db.jooq.historique.tables.Tracabilite

// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val TRACABILITE_PKEY: UniqueKey<Record> = Internal.createUniqueKey(Tracabilite.TRACABILITE, DSL.name("tracabilite_pkey"), arrayOf(Tracabilite.TRACABILITE.ID), true)
