/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.remocra.enums

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema
import remocra.db.jooq.remocra.Remocra
import javax.annotation.processing.Generated

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
    ],
    comments = "This class is generated by jOOQ",
)
@Suppress("warnings")
enum class TypeParametreRapportCourrier(@get:JvmName("literal") public val literal: String) : EnumType {
    CHECKBOX_INPUT("CHECKBOX_INPUT"),
    DATE_INPUT("DATE_INPUT"),
    NUMBER_INPUT("NUMBER_INPUT"),
    SELECT_INPUT("SELECT_INPUT"),
    TEXT_INPUT("TEXT_INPUT"),
    POINT("POINT"),
    POLYGON("POLYGON"),
    LINESTRING("LINESTRING"),
    ;
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Remocra.REMOCRA
    override fun getName(): String = "type_parametre_rapport_courrier"
    override fun getLiteral(): String = literal
}
