/*
 * This file is generated by jOOQ.
 */
package remocra.db.jooq.entrepotsig.tables.references

import remocra.db.jooq.entrepotsig.tables.VCommuneSig
import remocra.db.jooq.entrepotsig.tables.VVoieSig

/**
 * The table <code>entrepotsig.v_commune_sig</code>.
 */
val V_COMMUNE_SIG: VCommuneSig = VCommuneSig.V_COMMUNE_SIG

/**
 * The table <code>entrepotsig.v_voie_sig</code>.
 */
val V_VOIE_SIG: VVoieSig = VVoieSig.V_VOIE_SIG
